### ISSUE TITLE
DockerException is thrown when passing WebDriver to the constructor and running tests on Windows

### ISSUE THREAD

**Issue by vicajoy** [bonigarcia/selenium-jupiter#121]
**Description of the problem**: 

Used the following test:

    @TestMethodOrder(MethodOrderer.OrderAnnotation.class)
    @SingleSession
    @ExtendWith(SeleniumExtension.class)

    public class FailureCreatesScreenshotTest {

        private WebDriver driver;

        FailureCreatesScreenshotTest(WebDriver driver) {
            this.driver = driver;
        }

        @BeforeAll
        public static void setup() {
            WebDriverManager.iedriver().arch32().setup();
        }    

        @Test
        @Order(1)
        void testStep1() {
            step1(driver);
        }

        @Test
        @Order(2)
        void testStep2() {
            step2(driver);
        }

        private void step1(WebDriver driver) {
            driver.get("https://bonigarcia.github.io/selenium-jupiter/");
            assertTrue(driver.getTitle().contains("JUnit 5 extension for Selenium"));
        }

        private void step2(WebDriver driver) {
            WebElement about = driver.findElement(By.linkText("About"));
            about.click();
            assertFalse(about.isDisplayed());
        }

The browser is not starting as an exception is thrown (see the log). When I pass a specific driver (for example, InternetExplorerDriver or ChromeDriver) to the constructor, the tests do not throw an exception and the browser starts successfully.

**Browser and version**: Chrome, Firefox, Edge, Internet Explorer locally

**Operating system**: Windows 10

**Selenium-Jupiter version**: 3.4.0

Please note that everything works fine on `the selenium-jupiter-3.3.5` and below versions.

[log.log](https://github.com/bonigarcia/selenium-jupiter/files/5912914/log.log)

**Comment by bonigarcia** [comment]
I am developing a new major release of Selenium-Jupiter currently. This new version is going to change many things. I will try to implement a test to check this behavior in the new release.

**Comment by bonigarcia** [comment]
I'm analyzing this issue again. The problem here is that you are using the generic driver feature (i.e., a parameter of the type `WebDriver`). The default browser in the generic browser for Selenium-Jupiter 3.4.0 was `chrome-in-docker`. Looking in the logs, it seems it is not possible to connect to the Docker daemon in your Window host.

In any case, I am making a new major release of Selenium-Jupiter, in which the driver instantiation is completely different. I'm closing this issue now. Pleas stay tuned for the new version.
