### ISSUE TITLE
Add custom argument to @DockerBrowser

### ISSUE THREAD

**Issue by stevej2** [bonigarcia/selenium-jupiter#145]
I have a requirement to use docker browsers with imported certificates (client authentication pfx certificates). Each test could require a different certificate. 

During the first test, I can do this by using getContainerId and running commands on the docker container during the test. This isn't however possible on any subsequent tests (not sure why). 

A workaround is to create a customised docker image, before test execution, then change the configuration to use this amended image. Ie use a dockerfile to add RUN commands and save the image with a new label.

The only option I can currently think of is to use the "version" argument ie: type = CHROME, version = "testUser1". Although there might be a better way? This requires changing the selJup config to specify the image name. 

Ideally I would like to be able to run commands on the docker containers, or define the docker image name at test level.

**Comment by stevej2** [comment]
I can now execute code on the container in any test, by recasting SelenideDriver as a RemoteWebDriver.

**Comment by stevej2** [comment]
Unfortunately command line certificate importing is not a solution, as chrome would need restarting to pick up the new certificates. Importing certificates through the chrome UI is possible, however this would require automating the OS file open dialogue (not possible with selenium).

Along with "type" (mandatory) and "version" (optional). Could a "user" or "profile" (optional) argument be added?

i.e. type = CHROME, version = latest, user = test1 would search for image "selenoid/vnc:chrome_90.0_test1"

**Comment by bonigarcia** [comment]
In the next version of Selenium-Jupiter, a custom Docker image can be specified like [this](https://github.com/bonigarcia/selenium-jupiter/blob/master/src/test/java/io/github/bonigarcia/seljup/test/advance/CustomConfigWdmJupiterTest.java). Please stay tuned for the next version.
