### ISSUE TITLE
Parameterize tests with grid nodes

### ISSUE THREAD

**Issue by nicolaiparlog** [bonigarcia/selenium-jupiter#17]
I started using Selenium today and was delighted when I found out about this project. Big :+1:! I'm particularly impressed with the documentation. It's much better than so much else I had to read today that was _supposed_ to explain Selenium. :smiley:

I set up a Selenium grid on my machine and wanted to run each test once per node. As far as I could tell, this is not supported by Selenium Jupiter, right? [Template tests](https://gist.github.com/nicolaiparlog/138606fc0f3aeca1feae52805b540aa9#file-seleniumgrid-java) seemed to try to launch their own Docker images (which didn't work for some reason).

Since [I like JUnit 5 extensions](https://blog.codefx.org/design/architecture/junit-5-extension-model), I decided to write my own little extension that dynamically determines which nodes a grid contains and provides a `RemoteWebDriver` for each. [You can find the code in this snippet](https://gist.github.com/nicolaiparlog/138606fc0f3aeca1feae52805b540aa9) - it is not tested and documented, but it works on my machine. 😉

Would you be interested to include this functionality in Selenium Jupiter?

**Comment by nicolaiparlog** [comment]
Yes, Selenium Jupiter supports a Selenium grid. And it also supports parameterizing tests with `@TestTemplate` and `browsers.json`.

What I found missing was an easy way to use `@TestTemplate` and a Selenium Grid and run each test once per node:

```kotlin
@SeleniumGridTest
// executed once per node on the Selenium Grid
fun demo(driver: WebDriver) {
    driver.get("https://blog.codefx.org")
    val homeUrl = driver.findElement(By.className("img-hyperlink")).getAttribute("href")
    assertThat(homeUrl).contains("blog.codefx.org")
}
```

[My extension](https://gist.github.com/nicolaiparlog/138606fc0f3aeca1feae52805b540aa9#file-seleniumgridextension-java-L11-L17) does it this way:

```java
@Override
public Stream<TestTemplateInvocationContext> provideTestTemplateInvocationContexts(ExtensionContext context) {
	String url = SeleniumGridUrlFinder.find(context);
	return SeleniumGrid
		// find all nodes connected to the hub at `url`
		.nodes(url, context::publishReportEntry)
		// generate an invocation context for each node, leading to one invocation per node
		.map(SeleniumGridInvocationContext::new);
}
```

**Comment by bonigarcia** [comment]
Sorry for the late reply @nicolaiparlog. I'm back to Selenium-Jupiter, I am going to review all the open issues and release a new version as soon as possible.

Regarding your comments, yes, it seems a good idea to me. I think it could be implemented introducing a new field in the JSON for test template, as follows:

```
{
   "browsers": [
      [
         {
            "type": "chrome",
            "version": "latest",
            "driverUrl": "http://localhost:4444/wd/hub"
         }
      ],
      [
         {
            "type": "chrome-in-docker",
            "version": "latest"
         }
      ]
   ]
}
```

Internally, Selenium-Jupiter will parse this new field `driverUrl` using it to locate the Selenium Server. What do you think?

**Comment by bonigarcia** [comment]
This is available since version 3 of Selenium-Jupiter.

**Comment by nicolaiparlog** [comment]
Hey @bonigarcia, sorry for never replying to your question and thanks a ton for implementing this!. I just added a TODO in the project where I needed this and will try it out at some point. If I do and think there are improvements to be made, I'll let you know.
