### ISSUE TITLE
@TestTemplate together with @TestInstance(PER_CLASS)/@SingleSession

### ISSUE THREAD

**Issue by yvdv-one** [bonigarcia/selenium-jupiter#181]
Hi,

I started using selenium-jupiter a few weeks ago. I use @TestTemplate and provide two browsers (firefox and chrome) and a remote url to the selenium grid running in docker:

    @RegisterExtension
    SeleniumJupiter seleniumJupiter = new SeleniumJupiter();

    @BeforeAll
    void setup() {
        if (getProperties().remote() != null) {
            seleniumJupiter.getConfig().setSeleniumServerUrl(getProperties().remote());
        }
        if (getProperties().browsers().contains("firefox")) {
            BrowsersTemplate.Browser firefox = BrowserBuilder.firefox().build();
            seleniumJupiter.addBrowsers(firefox);
        }
        if (getProperties().browsers().contains("chrome")) {
            BrowsersTemplate.Browser chrome = BrowserBuilder.chrome().build();
            seleniumJupiter.addBrowsers(chrome);
        }
    }

I now try to combine @TestTemplate with @TestInstance(PER_CLASS)/@SingleSession to reduce the execution time of the test run, but a new driver instance is created for each testmethod/template instance.

I would expect the same driver instance to be reused for all tests of the same template instance in a class (e.g one firefox for all test methods and one chrome for all test methods).

I have scanned the code and found two possible issues in the SeleniumExtension:
1. In the teardown method the context Id is removed from the driverHandlerMap, even when SingleSession. It can therefore not be found in the resolveParameter method
2. The driverHandlerMap uses the extensionContext.getUniqueId() as its key. For template methods, this is an id containing the test class name/method name/template instance. When using singleSession, the method name should not be used as part of the key?

I am fairly new to JUnit5 and selenium-jupiter, so maybe I am misinterpreting things. In that case, please forgive my ignorance. If you could point me to the right direction that would be highly appreciated.

Best regards,
Yves

**Comment by bonigarcia** [comment]
I am developing a new major release of Selenium-Jupiter currently. This new version is going to change many things. I will try to implement a test to check this behavior in the new release.

**Comment by yvdv-one** [comment]
Thank you, it will be much appreciated.
I am using S-J both with local and remote grid and it is working like a charm. Thank you for this nice piece of software. If the above feature would work, it would speed up the test runs significantly.
Best regards,
Yves.

**Comment by bonigarcia** [comment]
I've been thinking in this issue, and I think the development version of Selenium-Jupiter (which has been significantly improved compared to latest release) works as expected, but I think it is not the same that you think.

Let me try to clarify.  The aim of `@TestTemplate` is to use different types of `WebDriver` with the same test logic. For instance, Chrome and Firefox using the same test logic (i.e., cross-browser testing).

For this reason, I think combining `@TestTemplate` and `@SingleSession` has not much sense, since `@SingleSession` reuse the same browser with different tests (something that typically does not happen with `@TestTemplate`, which is intended to use different types, and not the same browser).

In any case, things have changed significantly in the next version. Please stay tuned for it.

**Comment by yvdv-one** [comment]
Thank you for the explanation. 

My tests require a bootstrap procedure for login into the application and then navigate to the page under test. Doing this for every single test is very time-consuming. By running all tests in a class in the same browser instance, the tests are executed much faster. 

What I was hoping for is when using test templates for different browsers and combining it with SingleSession, s-j would keep the browser instances and re-use them in the next test template execution for the same browser on the same class. This would reduce the overall execution time significantly. 

My work-around is to rewrite the tests not to use test templates, and run the test project several times with different configuration properties for the different browsers. Each run will then be able to use SingleSession. The downside of this approach is that I have to trigger the Jenkins build running the test project several times in sequence with different configuration files and also the test results will be scattered over multiple builds.

Having said that, I really like s-j, it makes the setup of the tests much easier and I am looking forward to the new release.

Best regards, 
Yves.
