### ISSUE TITLE
Docker browser doesn't seem to be accepting proxy configuration in 4.0.0

### ISSUE THREAD

**Issue by MichielBugherJelli** [bonigarcia/selenium-jupiter#191]
**Description of the problem**: 
Proxy settings do not seem to be applying to chrome-in-docker images.
When we run our tests on the CI server, it requires a proxy to work properly.

We have code like this to set the proxy conditionally:
```
@ExtendWith(SeleniumJupiter.class)
public class BaseTest extends TestRailReporting {
	@Options
	static ChromeOptions options = new ChromeOptions();

	private static boolean optionsSet = false;

	@BeforeAll
	public static void beforeAll() {
		boolean isCI = Boolean.getBoolean("is.CI");

		if (isCI) {
			synchronized (BaseTest.class) {
				if (optionsSet) {
					return;
				}

				String proxyServerAddress = System.getProperty("https.proxy");

				// This is necessary only when running in Jenkins
				options.addArguments("--proxy-server=" + proxyServerAddress);

				optionsSet = true;
			}
		}
	}
}
```

If I try this on my local box, with the isCI set to true, it will fail when set to only `chrome` for `org.openqa.selenium.WebDriverException: unknown error: net::ERR_PROXY_CONNECTION_FAILED` (this expected as the proxy shouldn't work locally)
However, when I use `chrome-in-docker` all of the tests pass as if they are not attempting the proxy at all.

Also, on a final note, this all worked as expected before the update to 4.0.0.

**Browser and version**: 
```
{
  "browsers": [
    [
      {
        "type": "chrome-in-docker",
        "version": "91.0"
      }
    ]
  ]
}
```

**Operating system**: 
MacOS 11.5.2 (20G95) (Big Sur) x64

**Selenium-Jupiter version**: 
4.0.0

**Selenium-Jupiter use**: 
```
	@BeforeEach
	public void beforeEach(WebDriver driver) {
            ....
	}

	@TestTemplate
	public void iCanLoginAfterFailedAttempt() {
            ....
        }
```
**Selenium-Jupiter traces**: 
12:07:49.292  [ForkJoinPool-1-worker-5] ERROR io.github.bonigarcia.wdm.online.HttpClient - Error HTTP 404 executing https://chromedriver.storage.googleapis.com/LATEST_RELEASE_91.0
12:07:49.292  [ForkJoinPool-1-worker-5] WARN  io.github.bonigarcia.wdm.versions.VersionDetector - Exception reading https://chromedriver.storage.googleapis.com/LATEST_RELEASE_91.0 to get latest version of chromedriver (Error HTTP 404 executing https://chromedriver.storage.googleapis.com/LATEST_RELEASE_91.0)
12:07:49.293  [ForkJoinPool-1-worker-5] DEBUG io.github.bonigarcia.wdm.versions.VersionDetector - Getting driver version for chrome91.0 from online versions.properties
12:07:49.550  [ForkJoinPool-1-worker-5] DEBUG io.github.bonigarcia.wdm.versions.VersionDetector - Driver for chrome91.0 not found in online properties (using local versions.properties)
12:07:49.551  [ForkJoinPool-1-worker-5] DEBUG io.github.bonigarcia.wdm.WebDriverManager - The driver version for CHROME 91.0 is unknown ... trying with latest
12:07:49.733  [ForkJoinPool-1-worker-5] DEBUG io.github.bonigarcia.wdm.versions.VersionDetector - Latest version of chromedriver according to https://chromedriver.storage.googleapis.com/LATEST_RELEASE is 92.0.4515.107
12:07:49.746  [ForkJoinPool-1-worker-5] DEBUG io.github.bonigarcia.wdm.WebDriverManager - Driver chromedriver 92.0.4515.107 found in cache
12:07:49.747  [ForkJoinPool-1-worker-5] INFO  io.github.bonigarcia.wdm.WebDriverManager - Exporting webdriver.chrome.driver as /Users/mbugher/.cache/selenium/chromedriver/mac64/92.0.4515.107/chromedriver
12:07:52.300  [ForkJoinPool-1-worker-5] DEBUG io.github.bonigarcia.wdm.WebDriverManager - Quitting ChromeDriver: chrome on MAC (4df7b6c787d9abb4ce23435ed35b8a1a)

**Error trace**:

**Comment by MichielBugherJelli** [comment]
Tested with 4.0.1 and I still see the issue

**Comment by bonigarcia** [comment]
I am not able to reproduce this issue. I have just created an equivalent [test](https://github.com/bonigarcia/selenium-jupiter/blob/master/src/test/java/io/github/bonigarcia/seljup/test/template/TemplateRegisterOptionsTest.java) (i.e., a template test using options, Chrome, and Chrome in Docker) and everything seems to work nicely. I am not sure if this can be related to the Selenium WebDriver version you are you using (3 or 4).

**Comment by MichielBugherJelli** [comment]
> I am not sure if this can be related to the Selenium WebDriver version you are you using (3 or 4).

That seems to be the ticket. I wasn't aware of needing to be on selenium 4. I changed it to `4.0.0-rc-1` and it is working as expected. Thanks a ton, Boni ^_^
