### ISSUE TITLE
Allow specifying DriverOptions in superclass

### ISSUE THREAD

**Issue by komu** [bonigarcia/selenium-jupiter#2]
Sometimes it would be nice to make a common superclass for tests, specifying `DriverOptions` there. However, `AnnotationsReader.seekFieldAnnotatedWith` does not search superclasses when looking for fields. It would be a nice improvement if superclasses were considered as well.

**Comment by bonigarcia** [comment]
That's a good point. I'll take into account for next release.

**Comment by komu** [comment]
You may wish to checkout [org.junit.platform.commons.support.AnnotationSupport](http://junit.org/junit5/docs/5.0.0/api/org/junit/platform/commons/support/AnnotationSupport.html), which provides a maintained API for annotation access, supporting meta-annotations as well. It's an additional dependency (`org.junit.platform:junit-platform-commons`), but since `junit-platform-engine` depends on it, most users will already have it.

**Comment by bonigarcia** [comment]
Done. Available on version 1.2.0, just released.
