### ISSUE TITLE
@Options annotation is ignored when there is a superclass

### ISSUE THREAD

**Issue by jtougas** [bonigarcia/selenium-jupiter#20]
Looks like there is a missing `if (!out.isPresent())` condition here: 
https://github.com/bonigarcia/selenium-jupiter/blob/master/src/main/java/io/github/bonigarcia/AnnotationsReader.java#L147

which causes the `@Options` below to get ignored.
```
public class TestBase {
}

public class TestFoo extends TestBase {

    @Options
    ChromeOptions chromeOptions = new ChromeOptions();
    {
        chromeOptions.addArguments("--start-maximized");
    }

    @Test
    public void test(ChromeDriver webDriver) throws InterruptedException {
        webDriver.get("http://www.google.com");
        Thread.sleep(5000);
    }
}
```

**Comment by bonigarcia** [comment]
Thanks a lot for reporting @jtougas. Now it  has been fixed in the master branch, it will be available in the next version of Selenium-Jupiter.

**Comment by alrega** [comment]
@bonigarcia ,

Please check below case as well. I know `@DriverCapabilities` was ignored.
```
public class TestFoo {

    @Options
    ChromeOptions chromeOptions = new ChromeOptions();
    {
        chromeOptions.addArguments("--start-maximized");
    }

    @Nested
    class NestedTests {
        @Test
        public void test(ChromeDriver webDriver) throws InterruptedException {
            webDriver.get("http://www.google.com");
            Thread.sleep(5000);
        }
    }
}
```
@jtougas try implementing interface instead of extending base class as temporary workaround
