### ISSUE TITLE
Config option enableRecordingWhenFailure does not work for TestTemplate approach

### ISSUE THREAD

**Issue by danielFesenmeyer** [bonigarcia/selenium-jupiter#205]
**Description of the problem**: The config option enableRecording**WhenFailure** does not work for the TestTemplate approach. The corresponding setting is not evaluated when the WebDriverManager is configured. Therefore, no video recordings are created for failing tests.

The option enableRecording works as expected, but I don't like to use it, because I would like to have video recordings only in case of failure.

**Browser and version**: Latest version of Chrome in Docker.

**Operating system**:  20.04.2-Ubuntu, x86_64

**Selenium-Jupiter version**: 4.0.1

**Selenium-Jupiter use**:
Code like the one here: https://bonigarcia.dev/selenium-jupiter/#template-tests
But with additional setup code:  `seleniumJupiter.getConfig().enableRecordingWhenFailure();`

**Hint**:
Please have a look at the following line: https://github.com/bonigarcia/selenium-jupiter/blob/4203a3e51cae0b6f3997c003e8459342b39c26b9/src/main/java/io/github/bonigarcia/seljup/SeleniumJupiter.java#L329

It works for me, when I change this line to:
```
if (config.isRecording() || config.isRecordingWhenFailure()) {
```

**Comment by bonigarcia** [comment]
Thanks a lot for reporting. I have just pushed a fix to this issue.

**Comment by danielFesenmeyer** [comment]
Thanks a lot, @bonigarcia :smile::thumbsup:

**Comment by danielFesenmeyer** [comment]
Btw, when do you plan to release the next 4.x version? (It's not urgent, just like to know when I can plan to remove my patch from our codebase.)
