### ISSUE TITLE
docker-android does not work on OS X: Android device not ready: Could not access the Package Manager

### ISSUE THREAD

**Issue by DieterRogiest** [bonigarcia/selenium-jupiter#23]
Hi Boni,
selenium-jupiter using docker chrome and firefox works on my OS X.
But docker android fails:
I tried butomo1989/docker-android-arm-7.0:0.9-p5 and also the default 7.1.1.

it seems to fail on:
DockerDriverHandler - Android device not ready: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command '/root/platform-tools/adb -P 5037 -s emulator-5554 shell pm list packages com.android.chrome' exited with code 1'; Stderr: 'Error: Could not access the Package Manager.  Is the system running?'; Code: '1'

These arm emulators are very slow. Why aren't the x86 emulators used on OSX and Windows?

I think the adb command "...shell pm list packages com.android.chrome" maybe should start later?

I accessed the running container with docker command and ran ps auxwf to see the processes running in it.

I figured out the vnc url: 
docker ps:
0.0.0.0:32788->6080/tcp
http://localhost:32788/vnc.html and connect with password selenoid
and I took a screenshot: the android device is shown but its screen is only showing "android". (And the Appium Server window is spitting out log lines)

in the vm with 
cat /var/log/supervisor/appium.log
I could see those lines too and the last meaningful line was:

[Chromedriver] Error: Failed to start Chromedriver session: An operation did not complete before its timeout expired. (Original error: timeout: Adb command timed out after 30 seconds

At https://github.com/butomo1989/docker-android I read that to run these images on OS X one should have to run them in a vm in which docker would run, on Parallels Pro or Vmware Fusion. The Parallels trial is no Pro and with Vmware Fusion I was not able to start the vm created by docker-machine create command. 
Then I tried Virtualbox but that does not provide nested virtualization in the vm which is required by the butomo1989/docker-android-x86-8.1 container to run the android emulator. (https://www.virtualbox.org/ticket/4032 : 9 years and virtualbox still lacks this feature)

Paralles Pro and Vmware Fusion are supposed to have nested virtualization but the Fusion no longer works since I installed Virtualbox. I might uninstall Virtualbox but no guarantee that the changes that virtualbox did on my macbook pro OS X, will have been undone.

But I am not into docker technology, I am supposed to learn web automation skills and I would like to be able to test web sites with docker android in selenium-jupiter on my OS X.  

```
setup() {
SeleniumJupiter.config().setVnc(true);
SeleniumJupiter.config().setAndroidDeviceTimeoutSec(600); //increased from the default 200

public void testAndroid(
           @DockerBrowser(type = ANDROID, version = "7.0", deviceName = "Samsung Galaxy S6", browserName = "chrome") RemoteWebDriver driver) throws InterruptedException {
         // somewhere I read that someone had more luck with api 24 but that was with boot2docker I think

which I run with maven command:
mvn -f pom.xml -Dwdm.gitHubTokenName=DieterRogiest -Dwdm.gitHubTokenSecret=<mytoken> -Dwdm.forceCache clean surefire-report:report
```

And it fails with output:

```
15:44:04.036 [main] INFO io.github.bonigarcia.handler.DockerDriverHandler - Using Android version 7.0 (API level 24)
15:44:04.639 [main] INFO io.github.bonigarcia.DockerService - Starting Docker container butomo1989/docker-android-arm-7.0:0.9-p5
15:44:04.642 [main] DEBUG com.spotify.docker.client.DefaultDockerClient - Creating container with ContainerConfig: ...
15:44:04.832 [main] INFO com.spotify.docker.client.DefaultDockerClient - Starting container with Id: 5cab0343e7f7a084e5e96f0f471ba6ae259a18e6924158947068abf6d2dc4c92
15:44:05.323 [main] INFO io.github.bonigarcia.handler.DockerDriverHandler - Appium URL in Android device: http://localhost:32789/wd/hub
15:44:05.323 [main] INFO io.github.bonigarcia.handler.DockerDriverHandler - Android device name: Samsung Galaxy S6 -- Browser in Android device: chrome
15:44:05.323 [main] INFO io.github.bonigarcia.handler.DockerDriverHandler - Waiting for Android device ... this might take long, please wait (retries each 5 seconds)
15:44:05.552 [main] DEBUG io.github.bonigarcia.handler.DockerDriverHandler - Android device not ready: \n not found: limit=0 content=…
15:44:10.569 [main] DEBUG io.github.bonigarcia.handler.DockerDriverHandler - Android device not ready: \n not found: limit=0 content=…
15:45:21.009 [main] DEBUG io.github.bonigarcia.handler.DockerDriverHandler - Android device not ready: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command '/root/platform-tools/adb -P 5037 -s emulator-5554 shell pm list packages com.android.chrome' exited with code 1'; Stderr: 'Error: Could not access the Package Manager.  Is the system running?'; Code: '1'
...
15:54:01.679 [main] DEBUG io.github.bonigarcia.handler.DockerDriverHandler - Android device not ready: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command '/root/platform-tools/adb -P 5037 -s emulator-5554 shell wm size' timed out after 20000ms'; Stderr: ''; Code: 'null'
15:55:26.814 [main] ERROR io.github.bonigarcia.handler.DockerDriverHandler - Exception resolving driver in Docker (ANDROID 7.0)
io.github.bonigarcia.SeleniumJupiterException: Timeout (600 seconds) waiting for Android device in Docker
...
[ERROR] testAndroid{RemoteWebDriver}  Time elapsed: 689.357 s  <<< ERROR!
org.junit.jupiter.api.extension.ParameterResolutionException: Failed to resolve parameter [org.openqa.selenium.remote.RemoteWebDriver arg0] in method [public void dockertests.Test4DockerJupiter.testAndroid(org.openqa.selenium.remote.RemoteWebDriver) throws java.lang.InterruptedException]
Caused by: io.github.bonigarcia.SeleniumJupiterException: io.github.bonigarcia.SeleniumJupiterException: io.github.bonigarcia.SeleniumJupiterException: Timeout (600 seconds) waiting for Android device in Docker
Caused by: io.github.bonigarcia.SeleniumJupiterException: io.github.bonigarcia.SeleniumJupiterException: Timeout (600 seconds) waiting for Android device in Docker
Caused by: io.github.bonigarcia.SeleniumJupiterException: Timeout (600 seconds) waiting for Android device in Docker
```

**Comment by bonigarcia** [comment]
Indeed Selenium-Jupiter relies on the Docker images provided by butomo1989/docker-android. The support of these images on Windows and Mac OS X was discontinued some months ago. Reading again the doc, it seems it can be used again in Windows and Mac. In any case, I have already update the images used in Selenium-Jupiter to the latest tag of docker-android (1.5-p6 at the moment of this writing). It will be available by next version of Selenium-Jupiter, that is going to be released as soon as possible. Please try again when the new version is ready.

**Comment by bonigarcia** [comment]
For the best of my knowledge docker-android images can only be used natively in Linux. Versions 3.0.0 and 3.1.0 of Selenium-Jupiter use docker-android 1.5-p6, since newer versions (1.6*) have several relevant bugs and the time of writing.
