### ISSUE TITLE
Broken link to Selenium WebDriver

### ISSUE THREAD

**Issue by danielFesenmeyer** [bonigarcia/selenium-jupiter#246]
Minor documentation issue: The link to Selenium WebDriver on the README page is broken. The new URL seems to be https://www.selenium.dev/documentation/webdriver/.

**Comment by bonigarcia** [comment]
Thanks for reporting. It is fixed now.

**Comment by danielFesenmeyer** [comment]
Great, thanks for adjusting it so quickly.
