### ISSUE TITLE
example mobile emulation feature (with @DriverCapabilities) does not work

### ISSUE THREAD

**Issue by DieterRogiest** [bonigarcia/selenium-jupiter#25]
Hi,
the example for mobile emulation feature provided out of the box by Chrome with @DriverCapabilities at https://bonigarcia.github.io/selenium-jupiter/#remote-browsers (but it is not for remote-browsers of course) does not work for me: 
the chrome browser that appears does not render the web page using small screen resolutions to emulate the smartphone Nexus 5.
I'm on OS X with second latest Chrome browser (in its DevTools clicking on Toggle Device Toolbar opens the UI in a mobile view alright).
Maybe google changed something about it in chromeOptions? 

the code for that example is also at:
https://github.com/bonigarcia/selenium-jupiter/blob/master/src/test/java/io/github/bonigarcia/test/advance/ChromeWithGlobalCapabilitiesJupiterTest.java

**Comment by DieterRogiest** [comment]
OK,
Passing capabilities to ChromeDriver constructor (what Selenium-Jupiter does with its SeleniumExtension and its @DriverCapabilities I assume) is Deprecated from v3.6.0 (selenium) (see 
https://stackoverflow.com/questions/23834413/pass-driver-chromeoptions-and-desiredcapabilities).

http://chromedriver.chromium.org/mobile-emulation says to use "new ChromeDriver(chromeOptions)"

**Boni**, I think you should update Selenium-Jupiter for this.
So without Selenium-Jupiter I can get a small screen resolution that emulates a smartphone:

```
        public WebDriver driver;

        Map<String, String> mobileEmulation = new HashMap<>();
        mobileEmulation.put("deviceName", "Nexus 5");
        ChromeOptions chromeOptions = new ChromeOptions();
        chromeOptions.setExperimentalOption("mobileEmulation", mobileEmulation);
        driver = new ChromeDriver(chromeOptions);

    @AfterEach
    public void teardown() {
        if (driver != null) {
            driver.quit();
        }
    }

    public void timeDelay(long t) {   //TODO put this in one of the utility classes
        try {
            Thread.sleep(t);
        } catch (InterruptedException e) {}
    }

    @Test
    void chromeTest() {
        driver.get("https://bonigarcia.github.io/selenium-jupiter/");
        timeDelay(10000);
        assertThat(driver.getTitle(),
                containsString("JUnit 5 extension for Selenium"));
    }
```

**Comment by bonigarcia** [comment]
In fact that example was broken. The use of capabilities and options is actually a headache in Selenium. The problem I see is that it is not possible to merge capabilities with options, even if the method `merge` is available in the Selenium class `MutableCapabilities`. That's what Selenium-Jupiter does internally and it is not working for every scenario.

All in all, in order to fix the example, the solution I find is directly using options instead of capabilities, something similar to this:

```
@ExtendWith(SeleniumExtension.class)
public class ChromeWithGlobalCapabilitiesJupiterTest {

    @Options
    ChromeOptions options = new ChromeOptions();
    {
        Map<String, String> mobileEmulation = new HashMap<>();
        mobileEmulation.put("deviceName", "Nexus 5");
        options.setExperimentalOption("mobileEmulation", mobileEmulation);
    }

    @Test
    void chromeTest(ChromeDriver driver) {
        driver.get("https://bonigarcia.github.io/selenium-jupiter/");
        assertThat(driver.getTitle(),
                containsString("JUnit 5 extension for Selenium"));
    }

}


```
