### ISSUE TITLE
local grid example outputs an enormous amount of useless lines: how to suppress?

### ISSUE THREAD

**Issue by DieterRogiest** [bonigarcia/selenium-jupiter#26]
from https://bonigarcia.github.io/selenium-jupiter/#remote-browsers I'm playing with the local grid example (complete example: https://github.com/bonigarcia/selenium-jupiter/blob/master/src/test/java/io/github/bonigarcia/test/advance/RemoteWebDriverJupiterTest.java ).

I run it with command
mvn -f pom.xml -Dwdm.gitHubTokenName=<myname> -Dwdm.gitHubTokenSecret=<mytoken> -Dwdm.forceCache clean surefire-report:report

It spits out an enormous amount of DEBUG lines that make it hard to see INFO lines or my own println statements. Even when piped to "grep -v DEBUG" there are a lot of other useless lines that are more difficult to grep out.
Is there a way to suppress these lines?
I think this is only selenium-jupiter specific as only this clever example starts local hub and notes from the test code.
I asked this question also in https://groups.google.com/forum/#!forum/selenium-users (but it still needs to be approved by an admin)

**Comment by bonigarcia** [comment]
Try redirecting the error output to `/dev/null`:

`mvn test -Dtest=RemoteWebDriverJupiterTest 2>/dev/null`
