### ISSUE TITLE
Headless Chrome argument only works with parameter level @DriverOptions

### ISSUE THREAD

**Issue by HorvathDanielAndras** [bonigarcia/selenium-jupiter#3]
I am trying to create a test suite with headless chrome test cases only, and I ran into trouble of finding a clean and less verbose solution instead of: 

`@Test 
public void headlessTest(@DriverOptions(options = { @Option(name = "args", value = "--headless") }) ChromeDriver driver) { ... }`

I was trying to use other ways, but no other seems to add headless property to the driver: 

```
        @DriverOptions
	ChromeOptions chromeOptions = new ChromeOptions();
	{
		chromeOptions.setHeadless(true);
	}
	@Test
	public void headlessTest(ChromeDriver driver) { ... }
```
```
@Retention(RetentionPolicy.RUNTIME)
@Target({ ElementType.PARAMETER, ElementType.FIELD })
public @interface ChromeHeadless {

	public Option[] options() default {@Option(name = "args", value = "--headless")} ;
}
```

Is there  a work around for this?

**Comment by bonigarcia** [comment]
This option is working for me:

    @DriverOptions
    ChromeOptions chromeOptions = new ChromeOptions();
    {
        chromeOptions.setHeadless(true);
    }

... which is equivalent to:

    @DriverOptions
    ChromeOptions chromeOptions = new ChromeOptions();
    {
        chromeOptions.addArguments("--headless");
    }

Which version of Selenium WebDriver are you using?

**Comment by HorvathDanielAndras** [comment]
I am using Selenium 3.8.1 and selenium-jupiter 1.2.0.  Here is my build.gradle:
`// Apply the java-library plugin to add support for Java Library
apply plugin: 'java-library'

buildscript {

	repositories {
      mavenCentral()
      maven {
      	url "https://plugins.gradle.org/m2/"
    	}
               
	}
	dependencies {
        classpath 'org.junit.platform:junit-platform-gradle-plugin:1.0.2'
    }
}

apply plugin: 'org.junit.platform.gradle.plugin'

repositories {
  mavenCentral()
  
    }


configurations {
    junitXmlToHtml
}

dependencies {
    // This dependency is exported to consumers, that is to say found on their compile classpath.
    api 'org.apache.commons:commons-math3:3.6.1'

    // This dependency is used internally, and not exposed to consumers on their own compile classpath.
    implementation 'com.google.guava:guava:23.0'

    compile group: 'org.seleniumhq.selenium', name: 'selenium-java', version: '3.8.1'

	// To avoid compiler warnings about @API annotations in JUnit code.
	compile('org.apiguardian:apiguardian-api:1.0.0')

    compile('org.junit.jupiter:junit-jupiter-api:5.1.0-M1')

	// We implement `TestEngine` interface.
	compile('org.junit.platform:junit-platform-engine:1.1.0-M1')

	// https://mvnrepository.com/artifact/io.github.bonigarcia/selenium-jupiter
	compile group: 'io.github.bonigarcia', name: 'selenium-jupiter', version: '1.2.0'


	// https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter-params
	compile group: 'org.junit.jupiter', name: 'junit-jupiter-params', version: '5.1.0-M1'


    testCompile('org.junit.jupiter:junit-jupiter-api:5.1.0-M1')
    
    // https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter-params
    testCompile group: 'org.junit.jupiter', name: 'junit-jupiter-params', version: '5.1.0-M1'
    
 
	// Needed to run JUnit Jupiter tests.
	testRuntime('org.junit.jupiter:junit-jupiter-engine:5.1.0-M1')

	// Needed to run JUnit Platform on the console.
	testRuntime('org.junit.platform:junit-platform-console:1.1.0-M1')
	
	testRuntime("org.apache.logging.log4j:log4j-core:2.10.0")
	testRuntime("org.apache.logging.log4j:log4j-jul:2.10.0")
	
	junitXmlToHtml 'org.apache.ant:ant-junit:1.9.7'

}

junitPlatform {
    platformVersion '1.0.2' // optional, defaults to plugin version
    logManager 'org.apache.logging.log4j.jul.LogManager'
    reportsDir file('build/test-results/junit-platform') // this is the default  
    // enableStandardTestTask true
    // selectors (optional)
    // filters (optional)
}

junitPlatformTest.dependsOn cleanTest


task generateHtmlTestReports << {
    def reportsDir = new File(buildDir, 'test-reports')
    reportsDir.mkdirs()

    ant.taskdef(
        name: 'junitReport',
        classname: 'org.apache.tools.ant.taskdefs.optional.junit.XMLResultAggregator',
        classpath: configurations.junitXmlToHtml.asPath
    )

    ant.junitReport(todir: "$buildDir/test-results/junit-platform", tofile: "aggregated-test-results.xml") {
        fileset(dir: "$buildDir/test-results/junit-platform")
        report(format: 'frames', todir: reportsDir)
    }
}

afterEvaluate {
    def junitPlatformTestTask = tasks.getByName('junitPlatformTest')
    generateHtmlTestReports.dependsOn(junitPlatformTestTask)
    check.dependsOn(generateHtmlTestReports)
}
`

**Comment by HorvathDanielAndras** [comment]
I think I found the reason. My test class was extending a super class already besides `@ExtendWith(SeleniumExtension.class)`  and once I removed it, it was working. :)

Regarding my other question can custom annotations be applied to driver parameters?

```
@Retention(RetentionPolicy.RUNTIME)
@Target({ ElementType.PARAMETER, ElementType.FIELD })
public @interface ChromeHeadless {

	public Option[] options() default {@Option(name = "args", value = "--headless")} ;
}
```

**Comment by bonigarcia** [comment]
@HorvathDanielAndras No sorry, that cannot be done.

Nevertheless, my recommendation for you is to take a look to selenium-jupiter 2.0.0, just released. It reduces considerably the verbosity of annotations for arguments, among a lot of others new features.
