### ISSUE TITLE
How to setup different driver version for different browsers for a multi-browser scenario ?

### ISSUE THREAD

**Issue by aritra998** [bonigarcia/selenium-jupiter#34]
My scenario involves  using driver 5.16299 (not the latest) for edge and driver 72.0.3626.7 for chrome.
Can anyone please let me know how do I do this for local browsers ? (i.e. without docker)

**Comment by bonigarcia** [comment]
I'm working on this. It will be available in next version.

**Comment by bonigarcia** [comment]
You need to use version 3.0.0 of Selenium-Jupiter, recently released. Then, you need to configure the version of the driver using WebDriverManager before the tests, as follows:

```
WebDriverManager.chromedriver().version("72.0.3626.7");
WebDriverManager.edgedriver().version("5.16299");
```

You can find a similar example [here](https://github.com/bonigarcia/selenium-jupiter/blob/master/src/test/java/io/github/bonigarcia/seljup/test/advance/MultipleConfigWdmJupiterTest.java).

**Comment by aritra998** [comment]
Thanks a lot Boni :)
