### ISSUE TITLE
When DockerDriverHandler stats container with Android, it doesn't pass proxy settings

### ISSUE THREAD

**Issue by alrega** [bonigarcia/selenium-jupiter#36]
When DockerDriverHandler stats container with Android, it doesn't initialize environment variables "HTTP_PROXY", "HTTPS_PROXY", "NO_PROXY", "http_proxy", "https_proxy", "no_proxy"

Selenium Jupiter uses https://github.com/butomo1989/docker-android containers with android. According to the [documentation](https://github.com/butomo1989/docker-android/blob/master/README_CUSTOM_CONFIG.md) environment variables **HTTP_PROXY**, **HTTPS_PROXY**, **NO_PROXY** must be initialized for containers to operate behind proxy.

**Comment by bonigarcia** [comment]
Thanks @alrega. Merged.
