### ISSUE TITLE
java.lang.ClassNotFoundException: org.openqa.selenium.safari.SafariDriver

### ISSUE THREAD

**Issue by alexanderyellow** [bonigarcia/selenium-jupiter#4]
Hello! Try to use your tool. Example with @DockerBrowser. Environment: Windows 10. 
Run test and got exception: 
java.lang.NoClassDefFoundError: org/openqa/selenium/safari/SafariDriver
Caused by: java.lang.ClassNotFoundException: org.openqa.selenium.safari.SafariDriver.
Could you please help.

Source code:
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
@ExtendWith(SeleniumExtension.class)
public class DemoTest {

    @BeforeAll
    public void beforeAll() {
        System.out.println("before all");
    }

    @BeforeEach
    public void beforeEach() {
        System.out.println("before each");
    }

    @Test
    public void test1(@DockerBrowser(type = CHROME, version = "latest") RemoteWebDriver driver) {
        driver.get("https://google.com");
        System.out.println("test1");
    }

    @AfterAll
    public void afterAll() {
        System.out.println("after all");
    }

    @AfterEach
    public void afterEach() {
        System.out.println("after each");
    }
}

**Comment by bonigarcia** [comment]
Your problem is not clear. It seems to you are trying to use Chrome in a Docker container, but on the other side you say something about Safari, which is completely missing in the code snippet you copied.
