### ISSUE TITLE
Update docker-client dependency after https://github.com/spotify/docker-client/issues/1118 is fixed

### ISSUE THREAD

**Issue by alrega** [bonigarcia/selenium-jupiter#40]
https://github.com/spotify/docker-client/issues/1118 has valuable fix for proxy environment. 

Please update https://github.com/spotify/docker-client dependency after https://github.com/spotify/docker-client/issues/1118

**Comment by bonigarcia** [comment]
I am subscribed to that issue. Unfortunately, it seems that spotify/docker-client is not very active lately.

**Comment by bonigarcia** [comment]
Unfortunately that PR was closed automatically.

**Comment by alrega** [comment]
@bonigarcia , 
Good news. 
docker client 8.15.2 will include the necessary change. Please refer to PR https://github.com/spotify/docker-client/pull/1119

**Comment by bonigarcia** [comment]
@alrega I have just updated the dependency to the latest version. It will be available for next version.

**Comment by alrega** [comment]
@bonigarcia 
Thanks.
I checked Selenium Jupiter 3.2 with Docker Client 8.15.2 in my proxy environment. 
It works perfectly!
