### ISSUE TITLE
It is impossible to set a value of DriverCapabilities as boolean with @DriverCapabilities annotation

### ISSUE THREAD

**Issue by mainbong** [bonigarcia/selenium-jupiter#41]
I wanna test using multiple DriverCapabilities like below.
( client : selenium-jupiter, remote-server: selenoid docker(for chrome, for firefox), selenoid binary(for ie)
```java
public class BookMiddleSeleniumTest {

    @DriverUrl
    String url = "http://selenoid:4444/wd/hub";

    @Test
    @Tag("selenium")
    void testRequestForMobileWithSingleResultQueryAtRemoteIE(
            @DriverUrl("http://selenoid:4445/wd/hub")
            @DriverCapabilities("browserName=internet explorer")
                    RemoteWebDriver explorerDriver) {
        testMobileSearchBookResult(explorerDriver);
    }

    @Test
    @Tag("selenium")
    void testRequestForMobileWithSingleResultQueryAtRemoteChrome(
            @DriverCapabilities({"browserName=chrome", "enableVNC=true", "screenResolution=1920x1080x24"})
                    RemoteWebDriver chromeDriver) {
        testMobileSearchBookResult(chromeDriver);
    }

    @Test
    @Tag("selenium")
    void testRequestForMobileWithSingleResultQueryAtRemoteFirefoxDriver(
            @DriverCapabilities({"browserName=firefox", "enableVNC=true", "screenResolution=1920x1080x24"})
                    RemoteWebDriver firefoxDriver) {
        testMobileSearchBookResult(firefoxDriver);
    }
```

But you know, @DriverCapabilities annotation process all the parameters as String.
So `"enableVNC=true"` dosen't work propery, because of an exception `'Caused by: io.github.bonigarcia.SeleniumJupiterException: org.openqa.selenium.WebDriverException: json: cannot unmarshal string into Go struct field Caps.enableVNC of type bool'`

There is one way( as far as I know ) to add a boolean value in capability, like below.
```java
@DriverCapabilities
    DesiredCapabilities capabilities = new DesiredCapabilities();
    {
        capabilities.setCapability("browserName", "chrome");
        capabilities.setCapability("enableVNC", true);
    }
```
But It is impossible to use multiple with small change(e.g. change only 'browserName')...
And 
```yaml
sel.jup.vnc=true
sel.jup.vnc.screen.resolution=1920x1080x24
sel.jup.vnc.create.redirect.html.page=true
sel.jup.recording=true
sel.jup.recording.video.screen.size=1024x768
sel.jup.recording.video.frame.rate=12
```
in `selenium-jupiter.properties` are not available when I use not a DockerBrowser but a RemoteWebDriver. But There(The guide) was no mention of it.

Am I correct ? or is there some way to add a boolean value in DriverCapabilities?
If It is not, I think "enableVNC=true" should be parsed as <string, boolean> pair automatically.

Thanks for reading !

**Comment by bonigarcia** [comment]
I have just committed a patch implementing this. It will available by next version.
