### ISSUE TITLE
use shaded com.spotify:docker-client

### ISSUE THREAD

**Issue by kamkie** [bonigarcia/selenium-jupiter#43]
spotify docker client has dependency on old versions of guava and jersey
https://mvnrepository.com/artifact/com.spotify/docker-client/8.14.5

curently shaded version can't be used becouse io.github.bonigarcia.seljup.DockerService#getBindPort has a type mismatch on ImmutableMap

**Comment by bonigarcia** [comment]
I have just bump the version of docker-client to the latest stable version at writing time.

@kamkie Did you experience any exception in the former release?

**Comment by kamkie** [comment]
my problem is having jersey on classpath at all 

I have small spring boot app with mix of rest endpoints and html pages
this app have some rest tests and a few selenium tests 

I use this app for trening and as a technological demo

**Comment by bonigarcia** [comment]
Jersey is a transitive dependency of Selenium-Jupiter since it is used by docker-client. Docker support is critical for Selenium-Jupiter, so it is required to be there.

**Comment by kamkie** [comment]
docker-client-8.15.0-shaded.jar  has this dependency shaded with renamed packeges to support this usecase
