### ISSUE TITLE
TestTemplate enhancement request.

### ISSUE THREAD

**Issue by mainbong** [bonigarcia/selenium-jupiter#45]
TestTemplate is an awsome feature of seljup.
But there is no way to put specific capabilities in `browsers.json`.  (currently It looks like support type, version, url only..)
I wanna use it like below.
```
{
  "browsers": [
    [
      {
        "type": "internet explorer",
        "version": "11.0",
        "url": "http://selenoid:4444"
      }
    ],
    [
      {
        "type": "internet explorer",
        "version": "8.0",
        "url": "http://selenoid:4444"
      }
    ],
    [
      {
        "type": "internet explorer",
        "version": "9.0",
        "url": "http://selenoid:4444"
      }
    ],
    [
      {
        "type": "internet explorer",
        "version": "10.0",
        "url": "http://selenoid:4444"
      }
    ],
    [
      {
        "type": "chrome",
        "version": "71.0",
        "url": "http://selenoid:4444",
        "enableVNC": true,
        "screenResolution": "1920x1080x24"
      }
    ],
    [
      {
        "type": "firefox",
        "version": "64.0",
        "url": "http://selenoid:4444",
        "enableVNC": true,
        "screenResolution": "1920x1080x24"
      }
    ]
  ]
}
```

Have you some plan to support other capabilities in `TestTemplate` ? :)
I think It will be very useful feature !
Thanks

**Comment by bonigarcia** [comment]
Selenium-Jupiter 4 is out. Among other features, it allows arguments and preferences in [test templates](https://github.com/bonigarcia/selenium-jupiter/blob/master/src/test/resources/browsers-caps.json). Read the [doc](https://bonigarcia.dev/selenium-jupiter/) for more info.
