### ISSUE TITLE
okhttp version declared in pom.xml seems not correct.

### ISSUE THREAD

**Issue by Vladimir33** [bonigarcia/selenium-jupiter#46]
Hi, tried docker browser solution and got few exceptions at the very beginning, the image pull did not start.
The problem in my case was the version of okhttp declared in pom.xml as '3.12.0'. 
Looking in dependency tree found that the actual version of okhttp is '3.10.0', which will not work with retrofit 2.5.0 (due to one of the methods changed its signature...).
As far as I understand the '3.12.0' version of okhttp doesn't exist and the earlier one pulled instead (3.10.0).
To fix that I had to exclude okhttp and declare it with the latest version. That solved the issue.
Suppose the latest version of okhttp '3.12.1' should be declared in the pom.xml. Thanks

**Comment by bonigarcia** [comment]
I have just committed a patch bumping several dependencies versions (including okhttp).
