### ISSUE TITLE
java.lang.ClassNotFoundException: org.openqa.selenium.safari.SafariDriver

### ISSUE THREAD

**Issue by alexanderyellow** [bonigarcia/selenium-jupiter#5]
@bonigarcia Why did you close the issue??? I try to use Chrome, but get this error. I don't understand why this error because it's your code that i coped from the example. And i think you helped me but you have just closed issue.

java.lang.NoClassDefFoundError: org/openqa/selenium/safari/SafariDriver
Caused by: java.lang.ClassNotFoundException: org.openqa.selenium.safari.SafariDriver.
Could you please help.

Source code:
@testinstance(TestInstance.Lifecycle.PER_CLASS)
@ExtendWith(SeleniumExtension.class)
public class DemoTest {

@BeforeAll
public void beforeAll() {
    System.out.println("before all");
}

@BeforeEach
public void beforeEach() {
    System.out.println("before each");
}

@Test
public void test1(@DockerBrowser(type = CHROME, version = "latest") RemoteWebDriver driver) {
    driver.get("https://google.com");
    System.out.println("test1");
}

@AfterAll
public void afterAll() {
    System.out.println("after all");
}

@AfterEach
public void afterEach() {
    System.out.println("after each");
}

}

**Comment by bonigarcia** [comment]
That test is not valid, it does not compile. If you want support first learn how to code properly.
