### ISSUE TITLE
Run tests with same browser session

### ISSUE THREAD

**Issue by kamit78** [bonigarcia/selenium-jupiter#52]
Hi,

Currently every test create its webdriver session and once test done, webdriver session ends

But how can I run all tests with same webdriver session

**Comment by bonigarcia** [comment]
At this moment it is not possible. But I am going to implement this feature in next releases. It can be interesting, especially now that [JUnit 5 allows ordering tests](https://junit.org/junit5/docs/current/user-guide/#writing-tests-test-execution-order).

**Comment by kamit78** [comment]
Hi Bonigarcia,

When I can expect next release ?

**Comment by bonigarcia** [comment]
Version 3.2.0 of Selenium-Jupiter is out. In this version you can find a new annotation named `@SingleSession` which allows to do this. An example [here](https://bonigarcia.github.io/selenium-jupiter/#single-session).
