### ISSUE TITLE
Add ability to specify DriverCapabilities for RemoteWebDriver as a command line parameter

### ISSUE THREAD

**Issue by nguyenquoc** [bonigarcia/selenium-jupiter#54]
I would like to be able write a single test that uses the generic WebDriver configured to be either local or remote, with the browser specified on the command line. Currently, DriverCapabilities for the remote WebDriver can only be specified in source using something like:

`
@DriverCapabilities
Capabilities capabilities = firefox();
`

It would be great if this can be externalized as a command line parameter. It may be possible to use the existing parameter sel.jup.default.browser to define the @DriverCapabilities.

For example, for the generic test:

```
    @Test
    void genericTest(WebDriver driver) {
        driver.get("https://bonigarcia.github.io/selenium-jupiter/");
        assertThat(driver.getTitle(),
                containsString("JUnit 5 extension for Selenium"));

    }
```

I would like to run:

```
-Dsel.jup.selenium.server.url=http://my-grid:4444/wd/hub -Dsel.jup.default.browser=firefox
```

This would create a remote webdriver using firefox capabilities. If I didn't specify the arguments, then a local chromedriver would be created.

**Comment by bonigarcia** [comment]
Sorry for the late reply.

In fact, this is already supported in Selenium-Jupiter. I have just executed this test and it is working (using a remote browser in a local grid):

```
class GenericWithConfigTest {

    @RegisterExtension
    static SeleniumJupiter seleniumJupiter = new SeleniumJupiter();

    File imageFile;

    @BeforeAll
    static void setup() {
        seleniumJupiter.getConfig().setDefaultBrowser("firefox");
        seleniumJupiter.getConfig().setDefaultVersion("");
        seleniumJupiter.getConfig()
                .setSeleniumServerUrl("http://localhost:4444/wd/hub");
    }

    @Test
    void genericTest(WebDriver driver) {
        driver.get("https://bonigarcia.github.io/selenium-jupiter/");
        assertThat(driver.getTitle(),
                containsString("JUnit 5 extension for Selenium"));
    }

}
```

This test uses the config through the Java API, although it is equivalent to use the command line (`-Dsel.jup.selenium.server.url`, `sel.jup.default.browser`, etc). Notice the version is also necessary (empty string to use the latest). I am going to upload a new commit to avoid this empty string.

**Comment by bonigarcia** [comment]
The empty version is not required in the new version (3.4.0), just released.
