### ISSUE TITLE
Screenshot taken after @AfterEach cleanup method execution not showing actual failure reason

### ISSUE THREAD

**Issue by wuws** [bonigarcia/selenium-jupiter#61]
Hi, 
I have a question - currently screenshots are taken after @AfterEach method is executed which doesn't help a lot when I perform cleanup after test - I get screenshot of "item deleted" page instead of what actually was the issue. Is there a possiblity to make screenshot at the end of @Test method/during actual failure? Or is there any timeframe between failure and taking screenshot (maybe I execute cleanup too soon)?

**Comment by bonigarcia** [comment]
Currently the screenshot is being executed in the JUnit 5 extension callback `AfterEachCallback` (or `AfterAllCallback` in the case of using `@SingleSession`). See a picture from my JUnit 5 book:

![03-test-lifecycle-callbacks-with-extensions_v2](https://user-images.githubusercontent.com/5413013/58424426-a3522f00-8097-11e9-95d5-26aa109dd03e.png)


At this moment I am not sure if the logic for screenshot is worth to be moved to the `TestExecutionExceptionHandler`, I will consider it for future versions.

**Comment by ViliamS** [comment]
@wuws Below code should do the trick. 

@bonigarcia Thanks for your awesome work you did its top in the class... 
I just cant avoid feeling that you do not use it for every day QA testing as good Test Automation Framework should do not only in case of failure : 
1. execution log into file.
2. capture screenshot of failure - [missing point of passed test screenshots as it would usually end on logout page...]
3. dump html page source and store it to file in case of failure

For achieving that are AfterCallbacks poor choice to do the job... as what they usually manage is test data cleanups
- in case of complex bussiness applications we don't want to keep what failed test configured as well as we dont want to keep even what passed test did. And UI Automation frameworks dont have DB access to do so and For those purposes those callbacks are perfect as they still keep the test context variables.
In case you may use this simple change below :
One more time thanks for your work @!

`
public class FailureManager {

    final Logger log = getLogger(lookup().lookupClass());

    ExtensionContext context;
    Config           config;

    public FailureManager(ExtensionContext context, Config config) {
        this.context = context;
        this.config  = config;
    }

    void makeScreenshot(WebDriver driver, String fileName) {
        if (isScreenshotRequired() && driver != null && fileName != null) {
            String screenshotFormat = getConfig().getScreenshotFormat();
            switch (screenshotFormat) {
                case "png":
                    logFileScreenshot(driver, fileName);
                    break;
                case "base64":
                    logBase64Screenshot(driver, fileName);
                    break;
                case "base64andpng":
                    logBase64Screenshot(driver, fileName);
                    logFileScreenshot(driver, fileName);
                    break;
                default:
                    log.warn("Invalid screenshot format {}", screenshotFormat);
                    break;
            }
        }
    }

    boolean isScreenshotRequired() {
        Optional<Throwable> executionException = context.getExecutionException();
        String              screenshotAtTheEnd = getConfig().getScreenshotAtTheEndOfTests();
        return screenshotAtTheEnd.equalsIgnoreCase("true") || (executionException.isPresent() && screenshotAtTheEnd.equalsIgnoreCase("whenfailure"));
    }

    Config getConfig() {
        return config;
    }

    void logToFileHtmlPageDump(WebDriver driver, String fileName) {
        try {
            String outputFolder = getOutputFolder(context, getConfig().getOutputFolder());
            FileUtils.writeStringToFile(new File(outputFolder, "htmlPageDump_" + fileName + ".html"), driver.getPageSource(), "UTF-8");
        } catch (Exception e) {
            log.trace("Exception creating HTML page dump File", e);
        }
    }

    void logFileScreenshot(WebDriver driver, String fileName) {
        try {
            File   screenshotFile = ((TakesScreenshot) driver).getScreenshotAs(FILE);
            String outputFolder   = getOutputFolder(context, getConfig().getOutputFolder());
            copyFile(screenshotFile, new File(outputFolder, "screenshot_" + fileName + ".png"));
        } catch (Exception e) {
            log.trace("Exception creating screenshot as file", e);
        }
    }

    void logBase64Screenshot(WebDriver driver, String fileName) {
        try {
            String screenshotBase64 = ((TakesScreenshot) driver).getScreenshotAs(BASE64);
            log.info("Screenshot (in Base64) at the end of {} " + "(copy&paste this string as URL in browser to watch it):\r\n" + "data:image/png;base64,{}", fileName, screenshotBase64);
        } catch (Exception e) {
            log.trace("Exception creating screenshot in Base64", e);
        }
    }
}
`

`
public class SeleniumExtension extends io.github.bonigarcia.seljup.SeleniumExtension implements ParameterResolver, TestTemplateInvocationContextProvider, AfterEachCallback, AfterAllCallback, TestExecutionExceptionHandler, TestWatcher, BeforeTestExecutionCallback, BeforeAllCallback, BeforeEachCallback {

    static final String                                      CLASSPATH_PREFIX   = "classpath:";
    final        Logger                                      log                = getLogger(lookup().lookupClass());
    private      Config                                      config             = new Config();
    private      AnnotationsReader                           annotationsReader  = new AnnotationsReader();
    private      InternalPreferences                         preferences        = new InternalPreferences(getConfig());
    private      List<Class<?>>                              typeList           = new CopyOnWriteArrayList<>();
    public       Map<String, List<DriverHandler>>            driverHandlerMap   = new ConcurrentHashMap<>();
    private      Map<String, Class<?>>                       handlerMap         = new ConcurrentHashMap<>();
    private      Map<String, Class<?>>                       templateHandlerMap = new ConcurrentHashMap<>();
    private      Map<String, Map<String, DockerContainer>>   containersMap      = new ConcurrentHashMap<>();
    private      DockerService                               dockerService;
    private      Map<String, List<BrowsersTemplate.Browser>> browserListMap     = new ConcurrentHashMap<>();
    private      List<List<BrowsersTemplate.Browser>>        browserListList;

    public SeleniumExtension() {
        addEntry(handlerMap, "org.openqa.selenium.chrome.ChromeDriver", ChromeDriverHandler.class);
        addEntry(handlerMap, "org.openqa.selenium.firefox.FirefoxDriver", FirefoxDriverHandler.class);
        addEntry(handlerMap, "org.openqa.selenium.edge.EdgeDriver", EdgeDriverHandler.class);
        addEntry(handlerMap, "org.openqa.selenium.opera.OperaDriver", OperaDriverHandler.class);
        addEntry(handlerMap, "org.openqa.selenium.safari.SafariDriver", SafariDriverHandler.class);
        addEntry(handlerMap, "org.openqa.selenium.remote.RemoteWebDriver", RemoteDriverHandler.class);
        addEntry(handlerMap, "org.openqa.selenium.WebDriver", RemoteDriverHandler.class);
        addEntry(handlerMap, "io.appium.java_client.AppiumDriver", AppiumDriverHandler.class);
        addEntry(handlerMap, "java.util.List", ListDriverHandler.class);
        addEntry(handlerMap, "org.openqa.selenium.phantomjs.PhantomJSDriver", OtherDriverHandler.class);
        addEntry(handlerMap, "org.openqa.selenium.ie.InternetExplorerDriver", InternetExplorerDriverHandler.class);

        addEntry(templateHandlerMap, "chrome", ChromeDriver.class);
        addEntry(templateHandlerMap, "firefox", FirefoxDriver.class);
        addEntry(templateHandlerMap, "edge", EdgeDriver.class);
        addEntry(templateHandlerMap, "opera", OperaDriver.class);
        addEntry(templateHandlerMap, "safari", SafariDriver.class);
        addEntry(templateHandlerMap, "appium", AppiumDriver.class);
        addEntry(templateHandlerMap, "phantomjs", PhantomJSDriver.class);
        addEntry(templateHandlerMap, "iexplorer", InternetExplorerDriver.class);
        addEntry(templateHandlerMap, "internet explorer", InternetExplorerDriver.class);
        addEntry(templateHandlerMap, "chrome-in-docker", RemoteWebDriver.class);
        addEntry(templateHandlerMap, "firefox-in-docker", RemoteWebDriver.class);
        addEntry(templateHandlerMap, "opera-in-docker", RemoteWebDriver.class);
        addEntry(templateHandlerMap, "android", RemoteWebDriver.class);
    }

    private void addEntry(Map<String, Class<?>> map, String key, Class<?> value) {
        try {
            map.put(key, value);
        } catch (Exception e) {
            log.warn("Exception adding {}={} to handler map ({})", key, value, e.getMessage());
        }
    }

    @Override
    public boolean supportsParameter(ParameterContext parameterContext, ExtensionContext extensionContext) {
        Class<?> type = parameterContext.getParameter().getType();
        return (WebDriver.class.isAssignableFrom(type) || type.equals(List.class)) && !isTestTemplate(extensionContext);
    }

    @Override
    public Object resolveParameter(ParameterContext parameterContext, ExtensionContext extensionContext) {
        String    contextId = extensionContext.getUniqueId();
        Parameter parameter = parameterContext.getParameter();
        int       index     = parameterContext.getIndex();

        log.trace("Context id {}", contextId);
        if (isSingleSession(extensionContext) && driverHandlerMap.containsKey(contextId)) {
            List<DriverHandler> list = driverHandlerMap.get(contextId);
            if (index < list.size()) {
                Object obj = list.get(index).getObject();
                if (obj != null) {
                    log.trace("Returning index {}: {}", index, obj);
                    return obj;
                }
            }
        }

        Class<?>                 type    = parameter.getType();
        String                   url     = null;
        BrowsersTemplate.Browser browser = null;

        // Check template
        if (isGeneric(type) && !browserListMap.isEmpty()) {
            browser = getBrowser(contextId, index);
        }
        Optional<String> urlFromAnnotation = getUrlFromAnnotation(parameter, extensionContext);
        if (urlFromAnnotation.isPresent() && browser != null) {
            browser.setUrl(urlFromAnnotation.get());
        }
        if (browser != null) {
            type = templateHandlerMap.get(browser.getType());
            url  = browser.getUrl();
        }

        // Handler
        Class<?> constructorClass = handlerMap.containsKey(type.getName()) ? handlerMap.get(type.getName()) : OtherDriverHandler.class;
        boolean  isRemote         = constructorClass.equals(RemoteDriverHandler.class);
        if (url != null && !url.isEmpty()) {
            constructorClass = RemoteDriverHandler.class;
            isRemote         = true;
        }

        // WebDriverManager
        runWebDriverManagerIfNeded(type, isRemote);

        DriverHandler driverHandler = getDriverHandler(parameterContext, extensionContext, parameter, type, browser, constructorClass, isRemote);
        return resolveHandler(parameter, driverHandler);
    }

    private boolean isTestTemplate(ExtensionContext extensionContext) {
        Optional<Method> testMethod = extensionContext.getTestMethod();
        return testMethod.isPresent() && testMethod.get().isAnnotationPresent(TestTemplate.class);
    }

    @Override
    public void afterEach(ExtensionContext extensionContext) {
        teardown(extensionContext, !isSingleSession(extensionContext));
    }

    private void teardown(ExtensionContext extensionContext, boolean quitDriver) {
        // Make screenshots if required and close browsers
        FailureManager failureManager = new FailureManager(extensionContext, getConfig());

        String contextId = extensionContext.getUniqueId();
        log.trace("After each for context id {}", contextId);

        List<DriverHandler> driverHandlers = getValueFromContextId(driverHandlerMap, contextId);
        if (driverHandlers == null) {
            log.warn("Driver handler for context id {} not found", contextId);
            return;
        }

        for (DriverHandler driverHandler : copyOf(driverHandlers).reverse()) {
            // Quit WebDriver object
            Object object = driverHandler.getObject();
            try {
                quitWebDriver(object, quitDriver);
            } catch (Exception e) {
                log.warn("Exception closing webdriver object {}", object, e);
            }

            // Clean handler
            if (quitDriver) {
                try {
                    driverHandler.cleanup();
                } catch (Exception e) {
                    log.warn("Exception cleaning handler {}", driverHandler, e);
                }
            }
        }

        // Clear handler map
        driverHandlerMap.remove(contextId);
    }

    private boolean isSingleSession(ExtensionContext extensionContext) {
        boolean singleSession = extensionContext.getTestClass().isPresent() && extensionContext.getTestClass().get().isAnnotationPresent(SingleSession.class);
        log.trace("Single session {}", singleSession);
        return singleSession;
    }

    public Config getConfig() {
        return config;
    }

    private <T extends Object> T getValueFromContextId(Map<String, T> map, String contextId) {
        String newContextId = searchContextIdKeyInMap(map, contextId);
        return map.get(newContextId);
    }

    @SuppressWarnings("unchecked")
    private void quitWebDriver(Object object, boolean quitDriver) {
        if (object != null) {
            if (List.class.isAssignableFrom(object.getClass())) {
                List<RemoteWebDriver> webDriverList = (List<RemoteWebDriver>) object;
                for (int i = 0; i < webDriverList.size(); i++) {
//                    failureManager.makeScreenshot(webDriverList.get(i), driverHandler.getName() + "_" + i);
                    conditionalQuitWebDriver(webDriverList.get(i), quitDriver);
                }
            } else {
                WebDriver webDriver = (WebDriver) object;
//                failureManager.makeScreenshot(webDriver, driverHandler.getName());
                conditionalQuitWebDriver(webDriver, quitDriver);
            }
        }
    }

    private String searchContextIdKeyInMap(Map<String, ?> map, String contextId) {
        if (!map.containsKey(contextId)) {
            int i = contextId.lastIndexOf('/');
            if (i != -1) {
                contextId = contextId.substring(0, i);
            }
        }
        return contextId;
    }

    private void conditionalQuitWebDriver(WebDriver webDriver, boolean quitDriver) {
        if (quitDriver) {
            webDriver.quit();
        }
    }

    @Override
    public void afterAll(ExtensionContext extensionContext) throws Exception {
        if (!driverHandlerMap.isEmpty()) {
            teardown(extensionContext, true);
        }
    }

    @Override
    public boolean supportsTestTemplate(ExtensionContext context) {
        boolean allWebDriver = false;
        if (context.getTestMethod().isPresent()) {
            allWebDriver = !stream(context.getTestMethod().get().getParameterTypes()).map(s -> s.equals(WebDriver.class) || s.equals(RemoteWebDriver.class)).collect(toList()).contains(false);
        }
        return allWebDriver;
    }

    @Override
    public Stream<TestTemplateInvocationContext> provideTestTemplateInvocationContexts(ExtensionContext extensionContext) {
        String contextId = extensionContext.getUniqueId();
        try {
            // 1. By JSON content
            String browserJsonContent = getConfig().getBrowserTemplateJsonContent();
            if (browserJsonContent.isEmpty()) {
                // 2. By JSON file
                String browserJsonFile = getConfig().getBrowserTemplateJsonFile();
                if (browserJsonFile.startsWith(CLASSPATH_PREFIX)) {
                    String      browserJsonInClasspath = browserJsonFile.substring(CLASSPATH_PREFIX.length());
                    InputStream resourceAsStream       = this.getClass().getResourceAsStream("/" + browserJsonInClasspath);

                    if (resourceAsStream != null) {
                        browserJsonContent = IOUtils.toString(resourceAsStream, defaultCharset());
                    }

                } else {
                    browserJsonContent = new String(readAllBytes(get(browserJsonFile)));
                }
            }
            if (!browserJsonContent.isEmpty()) {
                return new Gson().fromJson(browserJsonContent, BrowsersTemplate.class).getStream().map(b -> invocationContext(b, this));
            }

            // 3. By setter
            if (browserListList != null) {
                return browserListList.stream().map(b -> invocationContext(b, this));
            }
            if (browserListMap != null) {
                return Stream.of(invocationContext(browserListMap.get(contextId), this));
            }

        } catch (IOException e) {
            throw new SeleniumJupiterException(e);
        }

        throw new SeleniumJupiterException("No browser scenario registered for test template");
    }

    private synchronized TestTemplateInvocationContext invocationContext(List<BrowsersTemplate.Browser> template, SeleniumExtension parent) {
        return new TestTemplateInvocationContext() {
            @Override
            public String getDisplayName(int invocationIndex) {
                return template.toString();
            }

            @Override
            public List<Extension> getAdditionalExtensions() {
                return singletonList(new ParameterResolver() {
                    @Override
                    public boolean supportsParameter(ParameterContext parameterContext, ExtensionContext extensionContext) {
                        Class<?> type = parameterContext.getParameter().getType();
                        return type.equals(WebDriver.class) || type.equals(RemoteWebDriver.class);
                    }

                    @Override
                    public Object resolveParameter(ParameterContext parameterContext, ExtensionContext extensionContext) {
                        String contextId = extensionContext.getUniqueId();
                        log.trace("Setting browser list {} for context id {}", template, contextId);
                        parent.browserListMap.put(contextId, template);

                        return parent.resolveParameter(parameterContext, extensionContext);
                    }
                });
            }
        };
    }

    private boolean isGeneric(Class<?> type) {
        return type.equals(RemoteWebDriver.class) || type.equals(WebDriver.class);
    }

    private BrowsersTemplate.Browser getBrowser(String contextId, int index) {
        BrowsersTemplate.Browser       browser     = null;
        List<BrowsersTemplate.Browser> browserList = getValueFromContextId(browserListMap, contextId);
        if (browserList == null) {
            log.warn("Browser list for context id {} not found", contextId);
        } else {
            if (index >= browserList.size()) {
                index = browserList.size() - 1;
            }
            browser = browserList.get(index);
        }
        return browser;
    }

    private Optional<String> getUrlFromAnnotation(Parameter parameter, ExtensionContext extensionContext) {
        Optional<String> out = empty();
        try {
            Optional<URL> urlFromAnnotation = annotationsReader.getUrl(parameter, extensionContext.getTestInstance(), config.getSeleniumServerUrl());
            if (urlFromAnnotation.isPresent()) {
                out = Optional.of(urlFromAnnotation.get().toString());
            }
        } catch (Exception e) {
            log.warn("Exception getting URL from annotation", e);
        }
        return out;
    }

    private void runWebDriverManagerIfNeded(Class<?> type, boolean isRemote) {
        if (!typeList.contains(type) && !isRemote) {
            WebDriverManager.getInstance(type).setup();
            typeList.add(type);
        }
    }

    private DriverHandler getDriverHandler(ParameterContext parameterContext, ExtensionContext extensionContext, Parameter parameter, Class<?> type, BrowsersTemplate.Browser browser, Class<?> constructorClass, boolean isRemote) {
        DriverHandler driverHandler = null;
        try {
            driverHandler = getDriverHandler(extensionContext, parameter, type, constructorClass, browser, isRemote);

            String contextId = extensionContext.getUniqueId();
            if (type.equals(RemoteWebDriver.class) || type.equals(WebDriver.class) || type.equals(List.class)) {
                initHandlerForDocker(contextId, driverHandler);
            }

            boolean isTemplate = isTestTemplate(extensionContext);
            if (!isTemplate && isGeneric(type) && isRemote) {
                ((RemoteDriverHandler) driverHandler).setParent(this);
                ((RemoteDriverHandler) driverHandler).setParameterContext(parameterContext);
            }

            putDriverHandlerInMap(extensionContext.getUniqueId(), driverHandler);

        } catch (Exception e) {
            handleException(parameter, driverHandler, constructorClass, e);
        }
        return driverHandler;
    }

    private Object resolveHandler(Parameter parameter, DriverHandler driverHandler) {
        if (driverHandler != null) {
            driverHandler.resolve();
            return driverHandler.getObject();
        } else if (getConfig().isExceptionWhenNoDriver()) {
            throw new SeleniumJupiterException("No valid handler for " + parameter + " was found");
        } else {
            return null;
        }
    }

    private DriverHandler getDriverHandler(ExtensionContext extensionContext, Parameter parameter, Class<?> type, Class<?> constructorClass, BrowsersTemplate.Browser browser, boolean isRemote) throws InstantiationException, IllegalAccessException, InvocationTargetException, NoSuchMethodException {
        DriverHandler driverHandler = null;
        if (isRemote && browser != null) {
            driverHandler = (DriverHandler) constructorClass.getDeclaredConstructor(Parameter.class, ExtensionContext.class, Config.class, AnnotationsReader.class, BrowsersTemplate.Browser.class).newInstance(parameter, extensionContext, getConfig(), getAnnotationsReader(), browser);

        } else if (constructorClass.equals(OtherDriverHandler.class) && !browserListMap.isEmpty()) {
            driverHandler = (DriverHandler) constructorClass.getDeclaredConstructor(Parameter.class, ExtensionContext.class, Config.class, AnnotationsReader.class, Class.class).newInstance(parameter, extensionContext, getConfig(), getAnnotationsReader(), type);

        } else {
            driverHandler = (DriverHandler) constructorClass.getDeclaredConstructor(Parameter.class, ExtensionContext.class, Config.class, AnnotationsReader.class).newInstance(parameter, extensionContext, getConfig(), getAnnotationsReader());

        }
        return driverHandler;
    }

    public void initHandlerForDocker(String contextId, DriverHandler driverHandler) {

        LinkedHashMap<String, DockerContainer> containerMap = new LinkedHashMap<>();
        driverHandler.setContainerMap(containerMap);
        log.trace("Adding new container map (context id {}) (handler {})", contextId, driverHandler);
        containersMap.put(contextId, containerMap);

        if (dockerService == null) {
            dockerService = new DockerService(config, preferences);
        }
        driverHandler.setDockerService(dockerService);
    }

    private void putDriverHandlerInMap(String contextId, DriverHandler driverHandler) {
        String newContextId = searchContextIdKeyInMap(driverHandlerMap, contextId);
        log.trace("Put driver handler {} in map (context id {}, new context id {})", driverHandler, contextId, newContextId);
        if (driverHandlerMap.containsKey(contextId)) {
            driverHandlerMap.get(contextId).add(driverHandler);
            log.trace("Adding {} to handler existing map (id {})", driverHandler, contextId);
        } else if (driverHandlerMap.containsKey(newContextId)) {
            driverHandlerMap.get(newContextId).add(driverHandler);
            log.trace("Adding {} to handler existing map (new id {})", driverHandler, newContextId);
        } else {
            List<DriverHandler> driverHandlers = new ArrayList<>();
            driverHandlers.add(driverHandler);
            driverHandlerMap.put(contextId, driverHandlers);
            log.trace("Adding {} to handler new map (id {})", driverHandler, contextId);
        }
    }

    private void handleException(Parameter parameter, DriverHandler driverHandler, Class<?> constructorClass, Exception e) {
        if (driverHandler != null && driverHandler.throwExceptionWhenNoDriver()) {
            log.error("Exception resolving {}", parameter, e);
            throw new SeleniumJupiterException(e);
        } else {
            log.warn("Exception creating {}", constructorClass, e);
        }
    }

    public AnnotationsReader getAnnotationsReader() {
        return annotationsReader;
    }

    public void putBrowserList(String key, List<BrowsersTemplate.Browser> browserList) {
        this.browserListMap.put(key, browserList);
    }

    public void addBrowsers(BrowsersTemplate.Browser... browsers) {
        if (browserListList == null) {
            browserListList = new ArrayList<>();
        }
        browserListList.add(asList(browsers));
    }

    public Optional<String> getContainerId(WebDriver driver) {
        try {
            for (Map.Entry<String, Map<String, DockerContainer>> entry : containersMap.entrySet()) {
                DockerContainer selenoidContainer = containersMap.get(entry.getKey()).values().iterator().next();
                URL             selenoidUrl       = new URL(selenoidContainer.getContainerUrl());
                URL             selenoidBaseUrl   = new URL(selenoidUrl.getProtocol(), selenoidUrl.getHost(), selenoidUrl.getPort(), "/");

                SelenoidService  selenoidService = new SelenoidService(selenoidBaseUrl.toString());
                Optional<String> containerId     = selenoidService.getContainerId(driver);

                if (containerId.isPresent()) {
                    return containerId;
                }
            }
            return empty();

        } catch (Exception e) {
            throw new SeleniumJupiterException(e);
        }
    }

    public DockerService getDockerService() {
        return dockerService;
    }

    public void clearPreferences() {
        preferences.clear();
    }

    @Override
    public void handleTestExecutionException(ExtensionContext extensionContext, Throwable throwable) throws Throwable {
        FailureManager failureManager = new FailureManager(extensionContext, getConfig());
        String         contextId      = extensionContext.getUniqueId();

        List<DriverHandler> driverHandlers = getValueFromContextId(driverHandlerMap, contextId);
        if (driverHandlers == null) {
            log.warn("Driver handler for context id {} not found", contextId);
            return;
        }
        for (DriverHandler driverHandler : copyOf(driverHandlers).reverse()) {
            Object object = driverHandler.getObject();

            if (object != null) {
                if (List.class.isAssignableFrom(object.getClass())) {
                    log.info("Detected List<RemoteWebDriver> instance so we are executing in container mode ....");
                    List<RemoteWebDriver> webDriverList = (List<RemoteWebDriver>) object;
                    for (int i = 0; i < webDriverList.size(); i++) {
                        log.info("i = " + i + " test instance exception handling....");
                        failureManager.logToFileHtmlPageDump(webDriverList.get(i), driverHandler.getName() + "_" + i);
                        failureManager.makeScreenshot(webDriverList.get(i), driverHandler.getName() + "_" + i);
                    }
                } else {
                    log.info("Detected WebDriver instance so we are executing in Local mode ....");
                    WebDriver webDriver = (WebDriver) object;
                    failureManager.logToFileHtmlPageDump(webDriver, driverHandler.getName());
                    failureManager.makeScreenshot(webDriver, driverHandler.getName());
                }
            } else {
                log.warn("WebDriver object is null !");
            }
        }
        throw throwable;
    }

    private void startingTest(ExtensionContext context) throws Exception {
        log.info(SciLog.logBox("Starting TEST -----> ", context.getDisplayName(), '='));
    }

    /**
     * Callback that is invoked <em>before</em> each test is invoked.
     *
     * @param context the current extension context; never {@code null}
     */
    public void beforeEach(ExtensionContext context) throws Exception {
        startingTest(context);
    }

    /**
     * Callback that is invoked once <em>before</em> all tests in the current
     * container.
     *
     * @param context the current extension context; never {@code null}
     */
    @Override
    public void beforeAll(ExtensionContext context) throws Exception {
        log.info(SciLog.logBox("Starting Testing Run ---> ", context.getUniqueId(), '#'));
    }

    /**
     * Callback that is invoked <em>immediately before</em> each test is executed.
     *
     * @param context the current extension context; never {@code null}
     */
    @Override
    public void beforeTestExecution(ExtensionContext context) throws Exception {
        startingTest(context);
    }

    /**
     * Invoked after a disabled test has been skipped.
     *
     * @param context the current extension context; never {@code null}
     * @param reason the reason the test is disabled; never {@code null}
     */
    @Override
    public void testDisabled(ExtensionContext context, Optional<String> reason) {
        log.warn(SciLog.logBox("Test Disabled because -----> ", reason.orElse(" for Unknown reason...."), '~'));
        context.getDisplayName();
        reason.ifPresent(s -> log.info("\n" + s));
    }

    /**
     * Invoked after a test has completed successfully.
     *
     * @param context the current extension context; never {@code null}
     */
    @Override
    public void testSuccessful(ExtensionContext context) {
        log.info(SciLog.logBox("Test Execution Successful -----> ", context.getDisplayName(), '#'));
    }

    /**
     * Invoked after a test has been aborted.
     *
     * @param context the current extension context; never {@code null}
     * @param cause   the throwable responsible for the test being aborted; may be {@code null}
     */
    @Override
    public void testAborted(ExtensionContext context, Throwable cause) {
        log.error(SciLog.logBox("Test Aborted -----> ", cause.getLocalizedMessage(), '!'));
    }

    /**
     * Invoked after a test has failed.
     *
     * @param context the current extension context; never {@code null}
     * @param cause   the throwable that caused test failure; may be {@code null}
     */
    @Override
    public void testFailed(ExtensionContext context, Throwable cause) {
        log.error(SciLog.logBox("Test " + context.getDisplayName() + " FAILED because -----> ", cause.toString(), '#'));
        cause.printStackTrace();
        if (context.getElement().isPresent()) {
            log.error("/n" + context.getElement().get().toString());
        }
    }

}
`

**Comment by ViliamS** [comment]
Ohh boy gitHub handling code blocks not very well here you may find the code in better formatting. 
[Link to online text storage service](https://textuploader.com/1dpp1)

**Comment by tuyentran81** [comment]
Hello @bonigarcia,
Our automation framework is using Selenium-Jupiter package. When I called the command as
```
mvn clean install -DskipTests && mvn clean test -pl=test-project -Dtest="com.project.automation.test.insight.customer.login.TC_002*" -Dspring.profiles.ac
tive="live" -Dsel.jup.screenshot.at.the.end.of.tests="whenfailure" -Dsel.jup.output.folder="screenshots"
```
But, I couldn't see the screenshot is created. Please help me if I am missing something.

**Comment by bonigarcia** [comment]
Selenium-Jupiter 4 is out. In the new release, screenshots (and recordings) are made in the `AfterTestExecutionCallback`. Check out the new [documentation](https://bonigarcia.dev/selenium-jupiter/) for further details.
