### ISSUE TITLE
Support AppiumServiceBuilder customizations 

### ISSUE THREAD

**Issue by mattmoskwa** [bonigarcia/selenium-jupiter#63]
**Description of the problem**: 
Currently seljup starts up a local appium service using the default options, as 

```
                    appiumDriverLocalService = AppiumDriverLocalService
                            .buildDefaultService();
```

It would be nice if we could customize the server options via seljup, like we can do with the `DesiredCapabilities`.

The specific use case is overriding the default "debug" log level, which makes for very verbose output in the console.

**Comment by garrisontaylor-toast** [comment]
A work around solution is to launch the server manually with the customized options and then specify its url using the `@DriverURL` annotation on either the parameter or on a field on the test. See https://bonigarcia.github.io/selenium-jupiter/#mobile-testing-with-appium for more information on the annotation. It would definitely be nice to have the configuration option though.

**Comment by bonigarcia** [comment]
PR merged.
