### ISSUE TITLE
[@Single Session] does not work

### ISSUE THREAD

**Issue by Dalyl09** [bonigarcia/selenium-jupiter#69]
My dependency for selenium, junit-jupiter and selenium-jupiter : 
<dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>3.141.59</version>
        </dependency>
        <dependency>
            <groupId>io.github.bonigarcia</groupId>
            <artifactId>selenium-jupiter</artifactId>
            <version>3.3.2</version>
            <scope>test</scope>
        </dependency>
 <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <version>${junit-jupiter.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.vintage</groupId>
            <artifactId>junit-vintage-engine</artifactId>
            <version>${junit-vintage.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-params</artifactId>
            <version>${junit-jupiter.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>${junit-jupiter.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.platform</groupId>
            <artifactId>junit-platform-launcher</artifactId>
            <version>1.4.0</version>
            <scope>test</scope>
        </dependency>
version : junit-jupiter : 5.4.0 and junit-vintage : 5.3.2

**Description of the problem**:

I would like run Single session several test my class test, but i can not:
 package com.xxxxxxxxx;

import static org.junit.jupiter.api.Assertions.assertTrue;

import org.junit.jupiter.api.MethodOrderer.OrderAnnotation;
import org.junit.jupiter.api.Order;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;
import org.junit.jupiter.api.extension.ExtendWith;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.Select;
import org.openqa.selenium.support.ui.WebDriverWait;

import io.github.bonigarcia.seljup.SeleniumExtension;
import io.github.bonigarcia.seljup.SingleSession;

import java.net.MalformedURLException;

@ExtendWith(SeleniumExtension.class)
@TestMethodOrder(OrderAnnotation.class)
@SingleSession
public class xxxxxxxTest {
    //Throw one by one test
    WebDriver webDriver;
    public xxxxxxxTest(ChromeDriver webDriver){
        this.webDriver = webDriver;
    }

    @Test
    @Order(1)
    public void shouldxxxxxxx() throws MalformedURLException, InterruptedException {

        webDriver.get("xxxxxxx");
        webDriver.findElement(By.name("xxxxxxx")).sendKeys("xxxxxxx");
        webDriver.findElement(By.name("xxxxxxx")).sendKeys("xxxxxxx");
        webDriver.findElement(By.cssSelector("xxxxxxx")).click();
        WebDriverWait wait = new WebDriverWait(webDriver, 10);
        wait.until(ExpectedConditions.visibilityOfElementLocated(By.name("xxxxxxx")));
        Select select = new Select(webDriver.findElement(By.name("xxxxxxx")));
        select.selectByValue("xxxxx");
        webDriver.findElement(By.cssSelector("xxxxxx")).click();
        
        assertTrue(xxxxxxxx);
    }

    @Test
    @Order(2)
    public void shouldxxxxxxx() throws MalformedURLException, InterruptedException {
        WebDriverWait wait = new WebDriverWait(webDriver, 10);
        wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("xxxxxxx")));
        webDriver.findElement(By.xpath("xxxxxxx")).click();
        WebDriverWait wait1 = new WebDriverWait(webDriver, 10);
        wait1.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("xxxxxxx")));
        webDriver.findElement(By.xpath("xxxxxxx")).click();
        WebDriverWait wait2 = new WebDriverWait(webDriver, 10);
        wait2.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//*[@id='xxxxx']")));
        webDriver.findElement(By.xpath("//*[@id='xxxxx']")).click();

    }

**Browser and version**:
 ChromeDriver 78.0.3904.70

**Operating system**: 
Windows 10, 64 bits.

org.junit.jupiter.api.extension.ParameterResolutionException: Failed to resolve parameter [org.openqa.selenium.chrome.ChromeDriver arg0] in constructor [public com.xxxxxxxxx(org.openqa.selenium.chrome.ChromeDriver)]:

**Comment by Dalyl09** [comment]
I resolved my problem : i add this :     @BeforeAll
    public void beforeClass(){
        this.webDriver = new ChromeDriver();
    }
without constructor

**Comment by bonigarcia** [comment]
Could you please post the complete error traces of your original error?

**Comment by Dalyl09** [comment]
I resolved my problem with : @BeforeAll
public void beforeClass(){
this.webDriver = new ChromeDriver();
}
Junit5  is not possible having a constructor

**Comment by bonigarcia** [comment]
> I resolved my problem with : @BeforeAll
> public void beforeClass(){
> this.webDriver = new ChromeDriver();
> }

That should not be necessary.

> Junit5 is not possible having a constructor

It should work. See for example [this](https://bonigarcia.github.io/selenium-jupiter/#single-session).

**Comment by Dalyl09** [comment]
For my side, your example with constructor i had error.

Thanks for your help (my problem is resolved and thanks for your job)
