### ISSUE TITLE
wsl 2 requires prefixing windows paths with /mnt

### ISSUE THREAD

**Issue by kamkie** [bonigarcia/selenium-jupiter#70]
wsl 2 requires prefixing windows paths with /mnt

I changed locally `io.github.bonigarcia.seljup.handler.DockerDriverHandler#getDockerPath` to 
```
            fileString = fileString.replace("\\", "/");
            fileString = fileString.replace(":", "");
            fileString = "/run/desktop/mnt/host/" + fileString;
```
and after that sharing files works again

**Comment by bonigarcia** [comment]
Thanks for reporting. To include your workaround in the master branch, it should be required to know if the Windows Subsystem for Linux is being used. Do you know how to do it from Java code?

**Comment by kamkie** [comment]
I think that to know that we habe wsl2 based docker desktop we would need to run `wsl - l` and check if docker desktop distro is on the list

maybe someone from docker desktop team can help

**Comment by kamkie** [comment]
i reported this also in docker desktop issue https://github.com/docker/for-win/issues/5066

**Comment by kamkie** [comment]
docker desktop edge 2.3.1.0 makes things better
only thing I needed to add was
```
    fileString = fileString.replace("\\", "/");
```


```
    private String getDockerPath(File file) {
        String fileString = file.getAbsolutePath();
        if (fileString.contains(":")) { // Windows
            fileString = toLowerCase(fileString.charAt(0))
                    + fileString.substring(1);
            fileString = fileString.replace("\\\\", "/");
            fileString = fileString.replace("\\", "/");
            fileString = fileString.replace(":", "");
            fileString = "/" + fileString;
        }
        log.trace("The path of file {} in Docker format is {}", file,
                fileString);
        return fileString;
    }
```

this looks backward compatible change
