### ISSUE TITLE
Documentation is out of sync with exampels

### ISSUE THREAD

**Issue by Bukama** [bonigarcia/selenium-jupiter#72]
Im reading the documentation to get an overview to the project (seems great so far!) but I noticed that the examples for `RemoteWebDriver` / `Capabilities` are out of sync.

The documentation writes about a `@BeforeAll` setUp method, but the example code doesn't show this method.

![docoutofsyncwithexamples](https://user-images.githubusercontent.com/4354359/77095994-fa523780-6a0e-11ea-9077-8b2b97251329.png)

Overall in the whole documentation the code examples often not fit 100% to the decription, which makes it difficutly to follow the documentation and get an overview.

**Comment by bonigarcia** [comment]
Thanks for reporting, I'll fix it for next version.

**Comment by bonigarcia** [comment]
Fixed in the doc of Selenium-Jupiter 3.3.5, just released.
