### ISSUE TITLE
Creating WebDriver hanging when using @Nested junit5 annotation

### ISSUE THREAD

**Issue by tyge68** [bonigarcia/selenium-jupiter#74]
**Description of the problem**: 
Starting of docker image is flaky
While most of the time it start well, it seems there is an issue with the selenoid image used as default.

**Browser and version**: default chrome

**Operating system**: Mac OS 10.15.3

**Selenium-Jupiter version**: 3.3.4
**Selenium-Jupiter use**: 
public class TestNestedIT {

  @RegisterExtension
  protected static SeleniumExtension seleniumExtension = new SeleniumExtension();

  @BeforeEach
  public void openGoogle(WebDriver driver) {
    WebDriverRunner.setWebDriver(driver);
    Selenide.open("https://www.google.com");
  }

  @Nested
  class MyNestedTest {
    @Test
    public void clickSearch() {
      final SelenideElement q = $("input[name=\"q\"]");
      q.sendKeys("some text", Keys.ENTER);
    }
  }

}

**Selenium-Jupiter traces**: 
16:06:26.257 [main] INFO  i.g.b.s.handler.DockerDriverHandler - Using CHROME version 81.0 (latest)
16:06:26.261 [main] INFO  i.g.bonigarcia.seljup.DockerService - Starting Docker container aerokube/selenoid:1.9.3
16:06:26.335 [main] INFO  c.s.d.client.DefaultDockerClient - Starting container with Id: afbaed87859e4c80695cee56af721e1f468f2d93a7f5ea17b3d6876182756667
--> hang here
**Error trace**: 
Shell command for docker
$ docker ps -a
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS              PORTS                     NAMES
afbaed87859e        aerokube/selenoid:1.9.3   "sh -c 'mkdir -p /et…"   18 minutes ago      Up 18 minutes       0.0.0.0:32771->4444/tcp   hopeful_archimedes

$ docker logs hopeful_archimedes
2020/04/23 16:06:26 [-] [INIT] [Loading configuration files...]
2020/04/23 16:06:26 [-] [INIT] [Loaded configuration from /etc/selenoid/browsers.json]
2020/04/23 16:06:26 [-] [INIT] [Video Dir: /opt/selenoid/video]
2020/04/23 16:06:26 [-] [INIT] [Using Docker API version: 1.35]
2020/04/23 16:06:26 [-] [INIT] [Timezone: Europe/Madrid]
2020/04/23 16:06:26 [-] [INIT] [Listening on :4444]
2020/04/23 16:06:26 [-] [NEW_REQUEST] [unknown] [172.17.0.1]

Adding trace level log shows this as the last lines:
17:20:30.558 [main] TRACE i.g.b.s.h.DockerDriverHandler - Selenium server URL http://localhost:32782/wd/hub
17:20:30.559 [main] TRACE i.g.b.s.h.DockerDriverHandler - Creating webdriver for CHROME latest (http://localhost:32782/wd/hub)
17:20:30.560 [main] DEBUG i.g.b.s.WebDriverCreator - Creating WebDriver for CHROME at http://localhost:32782/wd/hub with Capabilities {browserName: chrome, goog:chromeOptions: {args: [], extensions: []}, platform: ANY, version: }

It seems it doesn't have any timeout on that last request, eventually it should retry or quickly timeout (like less than 10 seconds).

Any idea how to make it more stable would be great. I was also thinking to only start one instance instance of having a clean environment per test run, but not sure how to do that properly, eventually using some pre-integration and post-integration in maven pom, but then it reduce the purpose of using this library...

**Comment by tyge68** [comment]
Another observation, usually when creating a session works, it logs  right after, and all goes well:
Apr 24, 2020 9:29:21 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
In my case for some tests it simply hang and do nothing, the container is started, and it wait on a socket read. After a few minutes not sure how long actually, it give up and then tries with local browser, which works then.

**Comment by tyge68** [comment]
I narrowed it down to the @Nested annotation usage, it seems this make it fails to get the webdriver session with chrome-in-docker, on a chrome (running locally) this is never an issue.

**Comment by tyge68** [comment]
So Nested + any Before in the parent class doesn't work with docker (chrome-in-docker for example), but works fine using "chrome" alone.

I have update the description with a simple example to reproduce the issue.

**Comment by tyge68** [comment]
While putting trace level , I see that this method doesn't calculate the proper amount of required browsers.

https://github.com/bonigarcia/selenium-jupiter/blob/master/src/main/java/io/github/bonigarcia/seljup/handler/DockerDriverHandler.java#L1022

That's mainly because it doesn't seem to suppose that classes can be nested, it would need to also traverse the parent for any possible implementation of a method that would use the WebDriver, and so count it.

**Comment by tyge68** [comment]
@bonigarcia  would you have some time to review it ? also it seems the master branch is already broken as many tests are not passing, it would make sense to define a daily build of the master to catch it up earlier when it start to fail, as I see the last build was done 3 months ago...

**Comment by bonigarcia** [comment]
Hi @tyge68. Thanks a lot for contributing. I've reviewed for PR and it seems ok to be, it is merged now.

I plan to implement several new features and release a new version of Selenium-Jupiter before the summer. I maintain this project in my free time and it is not easy to find the proper moment. But I will, no worries.
