### ISSUE TITLE
Recording not deleted if folder is different than default value

### ISSUE THREAD

**Issue by tyge68** [bonigarcia/selenium-jupiter#76]
**Description of the problem**: 
While using the parameter to change the output folder , we observed that it stopped to delete recording when the option to only keep failing one is set.

**Browser and version**: not related

**Operating system**: Mac OS Catalina 10.15.4

**Selenium-Jupiter version**: 3.3.4

**Selenium-Jupiter use**:  not related

**Selenium-Jupiter traces**: 

15:17:38.666 [main] TRACE i.g.b.s.h.DockerDriverHandler - Renaming target/failures/8bde76974c7d117989df5a5db66d6d2e.mp4 to testUpdateDescriptionFieldSave_arg0_CHROME_81.0_8bde76974c7d117989df5a5db66d6d2e.mp4
15:17:38.667 [main] TRACE i.g.b.s.h.DockerDriverHandler - Deleting testUpdateDescriptionFieldSave_arg0_CHROME_81.0_8bde76974c7d117989df5a5db66d6d2e.mp4 (recordingWhenFailure=true)
15:17:38.668 [main] WARN  i.g.b.s.h.DockerDriverHandler - Exception waiting for recording testUpdateDescriptionFieldSave_arg0_CHROME_81.0_8bde76974c7d117989df5a5db66d6d2e.mp4

It seems it want to delete the file without adding the outputFolder in front unlike in the previous log (renaming).

**Comment by tyge68** [comment]
It seems to be due to this https://github.com/bonigarcia/selenium-jupiter/blob/master/src/main/java/io/github/bonigarcia/seljup/handler/DockerDriverHandler.java#L1192
When it renames the recording, it looses the parent path.

**Comment by bonigarcia** [comment]
Thanks for reporting. I'll try to fix this one for the next release.

**Comment by bonigarcia** [comment]
I've just seen you also send a PR. That's great, thanks a lot.
