### ISSUE TITLE
DefaultDockerClient should be configurable with BUFFERED RequestEntityProcessing

### ISSUE THREAD

**Issue by shanloid** [bonigarcia/selenium-jupiter#82]
**Description of the problem**:
When running Docker-based browser tests in Bitbucket Pipelines, containers cannot be created (see Bitbucket Pipeline error log below), so all tests fail. This seems to be due to Atlassian enforcing [this part of the Docker daemon spec](https://github.com/moby/moby/blob/master/docs/api/v1.24.md):

_A Content-Length header should be present in POST requests to endpoints that expect a body._

The Spotify Docker Client used in this extension by default uses CHUNKED RequestEntityProcessing (this is the default if not configured), meaning that it will not set a Content-Length header. Spotify [added support in 8.16.0](https://github.com/spotify/docker-client/commit/8ffc6e0ab258c3edefc1a16a5d00997440b5f86d) to allow this to be configured to permit BUFFERED processing, which will set the Content-Length header correctly.

Ideally we could specify BUFFERED or CHUNKED via a config property, and then use that value to configure the DefaultDockerClient.Builder when building the client within the DockerService.

**Browser and version**: Latest version of Chrome in Docker.

**Operating system**: Linux container within Bitbucket Pipeline

**Selenium-Jupiter version**: 3.3.4

**Bitbucket Pipeline Docker Log**
time="2020-07-09T00:35:46.245148096Z" level=error msg="AuthZRequest for POST /containers/create returned error: authorization denied by plugin pipelines: Invalid content length provided"

**Comment by bonigarcia** [comment]
I have just committed a patch implementing this. It will available in the next version, to be released soon.

**Comment by bonigarcia** [comment]
This is available in Selenium-Jupiter 3.3.5, just released.
