### ISSUE TITLE
DockerBrowser with Custom Network

### ISSUE THREAD

**Issue by msaiducar** [bonigarcia/selenium-jupiter#83]
**Description of the problem**: 

We are using TestContainers in our Selenium Tests, with Junit 5. We are using TestContainer's browser container. Putting all containers into same Network solves all DNS problems when making a request to some container from browser. 

However, we are having some trouble with chrome containers, therefore trying to replace with selenium-jupiter. As you can imagine, when we want to make a request from DockerBrowser to any of our container, we are getting the following error, simply dockerbrowser can't resolve the hostname.

`org.openqa.selenium.WebDriverException: unknown error: net::ERR_NAME_NOT_RESOLVED`

It would be so awesome to have opportunity to configure network of DockerBrowser. Is it possible in the current version ?

**Browser and version**: 

Latest chrome, firefox

**Operating system**: 

Ubuntu 20.04

**Selenium-Jupiter version**: 

3.3.4

**Comment by bonigarcia** [comment]
By default, the network used in the Docker containers is `bridge`. It can be changed using the configuration key `sel.jup.docker.network`. The same can be done directly using Java configuration, as follows:

```
import static io.github.bonigarcia.seljup.BrowserType.CHROME;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.RegisterExtension;
import org.openqa.selenium.WebDriver;

import io.github.bonigarcia.seljup.DockerBrowser;
import io.github.bonigarcia.seljup.SeleniumExtension;

class DockerTest {

    @RegisterExtension
    static SeleniumExtension seleniumExtension = new SeleniumExtension();

    @BeforeAll
    static void setup() {
        seleniumExtension.getConfig().setDockerNetwork("bridge");
    }

    @Test
    void test(@DockerBrowser(type = CHROME) WebDriver driver) {
        // ...
    }

}
```
