### ISSUE TITLE
Extension not compatible with RetryingTest or RepeatedIfExceptionsTest extensions

### ISSUE THREAD

**Issue by tyge68** [bonigarcia/selenium-jupiter#88]
**Description of the problem**: While using the annotations from other extensions like RetryingTest or RepeatedIfExceptionsTest extensions the test cannot start due to NullpointerException

**Browser and version**: not related

**Operating system**: not related

**Selenium-Jupiter version**: 3.3.4

**Selenium-Jupiter use**:  create a test that is annotated with @RetryingTest(3) from org.junitpioneer.jupiter.RetryingTest

**Selenium-Jupiter traces**:
.....
caught: java.lang.NullPointerException
│  │  │  │               	at io.github.bonigarcia.seljup.SeleniumExtension$1.getDisplayName(SeleniumExtension.java:586)
│  │  │  │               	at org.junit.jupiter.engine.descriptor.TestTemplateInvocationTestDescriptor.<init>(TestTemplateInvocationTestDescriptor.java:48)
│  │  │  │               	at org.junit.jupiter.engine.descriptor.TestTemplateTestDescriptor.createInvocationTestDescriptor(TestTemplateTestDescriptor.java:130)
│  │  │  │               	at org.junit.jupiter.engine.descriptor.TestTemplateTestDescriptor.lambda$execute$1(TestTemplateTestDescriptor.java:103)
│  │  │  │               	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
.....

**Error trace**: see above

**Comment by bonigarcia** [comment]
Thanks a lot for reporting. Merged!
