### ISSUE TITLE
Can’t use without internet connectivity

### ISSUE THREAD

**Issue by stevej2** [bonigarcia/selenium-jupiter#94]
I am trying to use selenium-Jupiter on a standalone machine (no connection to dockerhub etc). I have imported the necessary docker images to my local registry, however docker-client tries to connect to docker.io registry and no tests run. I have tried setting sel.jup.docker.hub.url to my local docker repository (not sure where this is used), but docker-client still tries to connect to default registry then fails. 

Is it possible to use standalone?

Many thanks for a great extension!

**Comment by stevej2** [comment]
discovered this is possible! Although still not sure where docker.hub.url config is used.

**Comment by stevej2** [comment]
My mistake. I still can't seem to get around using it standalone. The docker service seems to try and connect to docker registry, regardless of dockerhub url setting and having all images already available locally.

**Comment by bonigarcia** [comment]
This should be fixed in version 3.4.0, just released.
