### ISSUE TITLE
Replacing spotify/docker-client dependency

### ISSUE THREAD

**Issue by thyming** [bonigarcia/selenium-jupiter#96]
Hi! Thanks for creating and maintaining this project.
I'm running into various issues with the http transport used by spotify/docker-client that I don't believe can be overcome through configuration of this tool or that one, due to an assumption in that code that the JAX-RS implementation is Jersey. The https://github.com/docker-java/docker-java project does not suffer from this problem, and is actively maintained. Would you be open to a PR replacing this dependency?

**Comment by bonigarcia** [comment]
Hi @thyming. Indeed this is a problem I plan to solve right away. It is causing other issues (e.g. #86) and I want to get rid of spotify/docker-client. At this moment, I am considering two alternatives:

https://github.com/docker-java/docker-java
https://github.com/dmandalidis/docker-client

This first one seems more solid to me. In fact, I used that library at the beginning of the development of Selenium-Jupiter. The second one is a fork of the original spotify/docker-client. The transition should be easier using that one. In fact, I committed a patch yesterday using that fork, so it is already in the master branch. But I am not sure to use it in the next release. I am not completely sure if this fork is going to be maintained for long (nowadays it is, though).

Overall, yes, I would love a PR to use again to docker-java in Selenium-Jupiter. Please let me know if you are up for it.

**Comment by bonigarcia** [comment]
Thanks a lot for contributing. Your PR is merged now.
